type AutoGenerated struct {
	Definitions Definitions `json:"definitions"`
}
type Type struct {
	Type string `json:"type"`
	Const int `json:"const"`
}
type Name struct {
	Type string `json:"type"`
}
type Description struct {
	Type string `json:"type"`
}
type Required struct {
	Type string `json:"type"`
}
type Items struct {
	Type string `json:"type"`
	Enum []int `json:"enum"`
	Description string `json:"description"`
}
type ChannelTypes struct {
	Type string `json:"type"`
	Items Items `json:"items"`
}
type Properties struct {
	Type Type `json:"type"`
	Name Name `json:"name"`
	Description Description `json:"description"`
	Required Required `json:"required"`
	ChannelTypes ChannelTypes `json:"channel_types"`
}
type APIApplicationCommandChannelOption struct {
	Type string `json:"type"`
	Properties Properties `json:"properties"`
	AdditionalProperties bool `json:"additionalProperties"`
	Required []string `json:"required"`
}
type Properties struct {
	Type Type `json:"type"`
	Name Name `json:"name"`
	Description Description `json:"description"`
	Required Required `json:"required"`
}
type APIApplicationCommandOptionBaseEnum15707879492532621570787949030815707879490580 struct {
	Type string `json:"type"`
	Properties Properties `json:"properties"`
	Required []string `json:"required"`
	AdditionalProperties bool `json:"additionalProperties"`
}
type APIApplicationCommandInteractionDataChannelOption struct {
	Ref string `json:"$ref"`
}
type Value struct {
	Ref string `json:"$ref"`
}
type Properties struct {
	Name Name `json:"name"`
	Type Type `json:"type"`
	Value Value `json:"value"`
}
type APIInteractionDataOptionBaseEnum15707879492532621570787949030815707879490580Snowflake struct {
	Type string `json:"type"`
	Properties Properties `json:"properties"`
	Required []string `json:"required"`
	AdditionalProperties bool `json:"additionalProperties"`
}
type Snowflake struct {
	Type string `json:"type"`
	Description string `json:"description"`
}
type Definitions struct {
	APIApplicationCommandChannelOption APIApplicationCommandChannelOption `json:"APIApplicationCommandChannelOption"`
	APIApplicationCommandOptionBaseEnum15707879492532621570787949030815707879490580 APIApplicationCommandOptionBaseEnum15707879492532621570787949030815707879490580 `json:"APIApplicationCommandOptionBase<enum-1570787949-253-262-1570787949-0-308-1570787949-0-580>"`
	APIApplicationCommandInteractionDataChannelOption APIApplicationCommandInteractionDataChannelOption `json:"APIApplicationCommandInteractionDataChannelOption"`
	APIInteractionDataOptionBaseEnum15707879492532621570787949030815707879490580Snowflake APIInteractionDataOptionBaseEnum15707879492532621570787949030815707879490580Snowflake `json:"APIInteractionDataOptionBase<enum-1570787949-253-262-1570787949-0-308-1570787949-0-580,Snowflake>"`
	Snowflake Snowflake `json:"Snowflake"`
}