type AutoGenerated struct {
	Definitions []struct {
		APIApplicationCommandAttachmentOption struct {
			Ref string `json:"$ref"`
			Deprecated string `json:"deprecated"`
		} `json:"APIApplicationCommandAttachmentOption,omitempty"`
		APIApplicationCommandOptionBaseEnum84748279941242484748279904278474827990818 struct {
			Type string `json:"type"`
			Properties struct {
				Type struct {
					Type string `json:"type"`
					Const int `json:"const"`
				} `json:"type"`
				Name struct {
					Type string `json:"type"`
				} `json:"name"`
				Description struct {
					Type string `json:"type"`
				} `json:"description"`
				Required struct {
					Type string `json:"type"`
				} `json:"required"`
			} `json:"properties"`
			Required []string `json:"required"`
			AdditionalProperties bool `json:"additionalProperties"`
			Deprecated string `json:"deprecated"`
		} `json:"APIApplicationCommandOptionBase<enum-847482799-412-424-847482799-0-427-847482799-0-818>,omitempty"`
		APIApplicationCommandInteractionDataAttachmentOption struct {
			Ref string `json:"$ref"`
			Deprecated string `json:"deprecated"`
		} `json:"APIApplicationCommandInteractionDataAttachmentOption,omitempty"`
		APIInteractionDataOptionBaseEnum84748279941242484748279904278474827990818Snowflake struct {
			Type string `json:"type"`
			Properties struct {
				Name struct {
					Type string `json:"type"`
				} `json:"name"`
				Type struct {
					Type string `json:"type"`
					Const int `json:"const"`
				} `json:"type"`
				Value struct {
					Ref string `json:"$ref"`
				} `json:"value"`
			} `json:"properties"`
			Required []string `json:"required"`
			AdditionalProperties bool `json:"additionalProperties"`
			Deprecated string `json:"deprecated"`
		} `json:"APIInteractionDataOptionBase<enum-847482799-412-424-847482799-0-427-847482799-0-818,Snowflake>,omitempty"`
		Snowflake struct {
			Type string `json:"type"`
			Description string `json:"description"`
		} `json:"Snowflake,omitempty"`
		APIApplicationCommandBooleanOption struct {
			Ref string `json:"$ref"`
			Deprecated string `json:"deprecated"`
		} `json:"APIApplicationCommandBooleanOption,omitempty"`
		APIApplicationCommandOptionBaseEnum84748279935536484748279904278474827990818 struct {
			Type string `json:"type"`
			Properties struct {
				Type struct {
					Type string `json:"type"`
					Const int `json:"const"`
				} `json:"type"`
				Name struct {
					Type string `json:"type"`
				} `json:"name"`
				Description struct {
					Type string `json:"type"`
				} `json:"description"`
				Required struct {
					Type string `json:"type"`
				} `json:"required"`
			} `json:"properties"`
			Required []string `json:"required"`
			AdditionalProperties bool `json:"additionalProperties"`
			Deprecated string `json:"deprecated"`
		} `json:"APIApplicationCommandOptionBase<enum-847482799-355-364-847482799-0-427-847482799-0-818>,omitempty"`
		APIApplicationCommandInteractionDataBooleanOption struct {
			Ref string `json:"$ref"`
			Deprecated string `json:"deprecated"`
		} `json:"APIApplicationCommandInteractionDataBooleanOption,omitempty"`
		APIInteractionDataOptionBaseEnum84748279935536484748279904278474827990818Boolean struct {
			Type string `json:"type"`
			Properties struct {
				Name struct {
					Type string `json:"type"`
				} `json:"name"`
				Type struct {
					Type string `json:"type"`
					Const int `json:"const"`
				} `json:"type"`
				Value struct {
					Type string `json:"type"`
				} `json:"value"`
			} `json:"properties"`
			Required []string `json:"required"`
			AdditionalProperties bool `json:"additionalProperties"`
			Deprecated string `json:"deprecated"`
		} `json:"APIInteractionDataOptionBase<enum-847482799-355-364-847482799-0-427-847482799-0-818,boolean>,omitempty"`
		APIApplicationCommandChannelOption struct {
			Type string `json:"type"`
			Properties struct {
				Type struct {
					Type string `json:"type"`
					Const int `json:"const"`
				} `json:"type"`
				Name struct {
					Type string `json:"type"`
				} `json:"name"`
				Description struct {
					Type string `json:"type"`
				} `json:"description"`
				Required struct {
					Type string `json:"type"`
				} `json:"required"`
				ChannelTypes struct {
					Type string `json:"type"`
					Items struct {
						Type string `json:"type"`
						Enum []int `json:"enum"`
						Description string `json:"description"`
						Deprecated string `json:"deprecated"`
					} `json:"items"`
				} `json:"channel_types"`
			} `json:"properties"`
			AdditionalProperties bool `json:"additionalProperties"`
			Required []string `json:"required"`
			Deprecated string `json:"deprecated"`
		} `json:"APIApplicationCommandChannelOption,omitempty"`
		APIApplicationCommandOptionBaseEnum84748279937238184748279904278474827990818 struct {
			Type string `json:"type"`
			Properties struct {
				Type struct {
					Type string `json:"type"`
					Const int `json:"const"`
				} `json:"type"`
				Name struct {
					Type string `json:"type"`
				} `json:"name"`
				Description struct {
					Type string `json:"type"`
				} `json:"description"`
				Required struct {
					Type string `json:"type"`
				} `json:"required"`
			} `json:"properties"`
			Required []string `json:"required"`
			AdditionalProperties bool `json:"additionalProperties"`
			Deprecated string `json:"deprecated"`
		} `json:"APIApplicationCommandOptionBase<enum-847482799-372-381-847482799-0-427-847482799-0-818>,omitempty"`
		APIApplicationCommandInteractionDataChannelOption struct {
			Ref string `json:"$ref"`
			Deprecated string `json:"deprecated"`
		} `json:"APIApplicationCommandInteractionDataChannelOption,omitempty"`
		APIInteractionDataOptionBaseEnum84748279937238184748279904278474827990818Snowflake struct {
			Type string `json:"type"`
			Properties struct {
				Name struct {
					Type string `json:"type"`
				} `json:"name"`
				Type struct {
					Type string `json:"type"`
					Const int `json:"const"`
				} `json:"type"`
				Value struct {
					Ref string `json:"$ref"`
				} `json:"value"`
			} `json:"properties"`
			Required []string `json:"required"`
			AdditionalProperties bool `json:"additionalProperties"`
			Deprecated string `json:"deprecated"`
		} `json:"APIInteractionDataOptionBase<enum-847482799-372-381-847482799-0-427-847482799-0-818,Snowflake>,omitempty"`
		APIApplicationCommandIntegerOption struct {
			Ref string `json:"$ref"`
			Deprecated string `json:"deprecated"`
		} `json:"APIApplicationCommandIntegerOption,omitempty"`
		APIApplicationCommandOptionWithAutocompleteOrChoicesWrapperInterface630667610254738630667610013671295383896APIApplicationCommandOptionChoiceNumber struct {
			AnyOf []struct {
				Type string `json:"type"`
				AdditionalProperties bool `json:"additionalProperties"`
				Properties struct {
					Autocomplete struct {
						Type string `json:"type"`
						Const bool `json:"const"`
					} `json:"autocomplete"`
					Type struct {
						Type string `json:"type"`
						Const int `json:"const"`
					} `json:"type"`
					Name struct {
						Type string `json:"type"`
					} `json:"name"`
					Description struct {
						Type string `json:"type"`
					} `json:"description"`
					Required struct {
						Type string `json:"type"`
					} `json:"required"`
					MinValue struct {
						Type string `json:"type"`
						Description string `json:"description"`
					} `json:"min_value"`
					MaxValue struct {
						Type string `json:"type"`
						Description string `json:"description"`
					} `json:"max_value"`
				} `json:"properties,omitempty"`
				Required []string `json:"required"`
				Properties0 struct {
					Autocomplete struct {
						Type string `json:"type"`
						Const bool `json:"const"`
					} `json:"autocomplete"`
					Choices struct {
						Type string `json:"type"`
						Items struct {
							Ref string `json:"$ref"`
						} `json:"items"`
					} `json:"choices"`
					Type struct {
						Type string `json:"type"`
						Const int `json:"const"`
					} `json:"type"`
					Name struct {
						Type string `json:"type"`
					} `json:"name"`
					Description struct {
						Type string `json:"type"`
					} `json:"description"`
					Required struct {
						Type string `json:"type"`
					} `json:"required"`
					MinValue struct {
						Type string `json:"type"`
						Description string `json:"description"`
					} `json:"min_value"`
					MaxValue struct {
						Type string `json:"type"`
						Description string `json:"description"`
					} `json:"max_value"`
				} `json:"properties,omitempty"`
			} `json:"anyOf"`
			Deprecated string `json:"deprecated"`
		} `json:"APIApplicationCommandOptionWithAutocompleteOrChoicesWrapper<interface-630667610-254-738-630667610-0-13671295383896,APIApplicationCommandOptionChoice<number>>,omitempty"`
		APIApplicationCommandOptionBaseEnum84748279934535484748279904278474827990818 struct {
			Type string `json:"type"`
			Properties struct {
				Type struct {
					Type string `json:"type"`
					Const int `json:"const"`
				} `json:"type"`
				Name struct {
					Type string `json:"type"`
				} `json:"name"`
				Description struct {
					Type string `json:"type"`
				} `json:"description"`
				Required struct {
					Type string `json:"type"`
				} `json:"required"`
			} `json:"properties"`
			Required []string `json:"required"`
			AdditionalProperties bool `json:"additionalProperties"`
			Deprecated string `json:"deprecated"`
		} `json:"APIApplicationCommandOptionBase<enum-847482799-345-354-847482799-0-427-847482799-0-818>,omitempty"`
		APIApplicationCommandOptionChoiceNumber struct {
			Type string `json:"type"`
			Properties struct {
				Name struct {
					Type string `json:"type"`
				} `json:"name"`
				Value struct {
					Type string `json:"type"`
				} `json:"value"`
			} `json:"properties"`
			Required []string `json:"required"`
			AdditionalProperties bool `json:"additionalProperties"`
			Description string `json:"description"`
			Deprecated string `json:"deprecated"`
		} `json:"APIApplicationCommandOptionChoice<number>,omitempty"`
		APIApplicationCommandInteractionDataIntegerOption struct {
			Type string `json:"type"`
			Properties struct {
				Name struct {
					Type string `json:"type"`
				} `json:"name"`
				Type struct {
					Type string `json:"type"`
					Const int `json:"const"`
				} `json:"type"`
				Value struct {
					Type string `json:"type"`
				} `json:"value"`
				Focused struct {
					Type string `json:"type"`
				} `json:"focused"`
			} `json:"properties"`
			AdditionalProperties bool `json:"additionalProperties"`
			Required []string `json:"required"`
			Deprecated string `json:"deprecated"`
		} `json:"APIApplicationCommandInteractionDataIntegerOption,omitempty"`
		APIInteractionDataOptionBaseEnum84748279934535484748279904278474827990818Number struct {
			Type string `json:"type"`
			Properties struct {
				Name struct {
					Type string `json:"type"`
				} `json:"name"`
				Type struct {
					Type string `json:"type"`
					Const int `json:"const"`
				} `json:"type"`
				Value struct {
					Type string `json:"type"`
				} `json:"value"`
			} `json:"properties"`
			Required []string `json:"required"`
			AdditionalProperties bool `json:"additionalProperties"`
			Deprecated string `json:"deprecated"`
		} `json:"APIInteractionDataOptionBase<enum-847482799-345-354-847482799-0-427-847482799-0-818,number>,omitempty"`
		APIApplicationCommandMentionableOption struct {
			Ref string `json:"$ref"`
			Deprecated string `json:"deprecated"`
		} `json:"APIApplicationCommandMentionableOption,omitempty"`
		APIApplicationCommandOptionBaseEnum84748279938940284748279904278474827990818 struct {
			Type string `json:"type"`
			Properties struct {
				Type struct {
					Type string `json:"type"`
					Const int `json:"const"`
				} `json:"type"`
				Name struct {
					Type string `json:"type"`
				} `json:"name"`
				Description struct {
					Type string `json:"type"`
				} `json:"description"`
				Required struct {
					Type string `json:"type"`
				} `json:"required"`
			} `json:"properties"`
			Required []string `json:"required"`
			AdditionalProperties bool `json:"additionalProperties"`
			Deprecated string `json:"deprecated"`
		} `json:"APIApplicationCommandOptionBase<enum-847482799-389-402-847482799-0-427-847482799-0-818>,omitempty"`
		APIApplicationCommandInteractionDataMentionableOption struct {
			Ref string `json:"$ref"`
			Deprecated string `json:"deprecated"`
		} `json:"APIApplicationCommandInteractionDataMentionableOption,omitempty"`
		APIInteractionDataOptionBaseEnum84748279938940284748279904278474827990818Snowflake struct {
			Type string `json:"type"`
			Properties struct {
				Name struct {
					Type string `json:"type"`
				} `json:"name"`
				Type struct {
					Type string `json:"type"`
					Const int `json:"const"`
				} `json:"type"`
				Value struct {
					Ref string `json:"$ref"`
				} `json:"value"`
			} `json:"properties"`
			Required []string `json:"required"`
			AdditionalProperties bool `json:"additionalProperties"`
			Deprecated string `json:"deprecated"`
		} `json:"APIInteractionDataOptionBase<enum-847482799-389-402-847482799-0-427-847482799-0-818,Snowflake>,omitempty"`
		APIApplicationCommandNumberOption struct {
			Ref string `json:"$ref"`
			Deprecated string `json:"deprecated"`
		} `json:"APIApplicationCommandNumberOption,omitempty"`
		APIApplicationCommandOptionWithAutocompleteOrChoicesWrapperInterface19109542592547361910954259013611295383896APIApplicationCommandOptionChoiceNumber struct {
			AnyOf []struct {
				Type string `json:"type"`
				AdditionalProperties bool `json:"additionalProperties"`
				Properties struct {
					Autocomplete struct {
						Type string `json:"type"`
						Const bool `json:"const"`
					} `json:"autocomplete"`
					Type struct {
						Type string `json:"type"`
						Const int `json:"const"`
					} `json:"type"`
					Name struct {
						Type string `json:"type"`
					} `json:"name"`
					Description struct {
						Type string `json:"type"`
					} `json:"description"`
					Required struct {
						Type string `json:"type"`
					} `json:"required"`
					MinValue struct {
						Type string `json:"type"`
						Description string `json:"description"`
					} `json:"min_value"`
					MaxValue struct {
						Type string `json:"type"`
						Description string `json:"description"`
					} `json:"max_value"`
				} `json:"properties,omitempty"`
				Required []string `json:"required"`
				Properties0 struct {
					Autocomplete struct {
						Type string `json:"type"`
						Const bool `json:"const"`
					} `json:"autocomplete"`
					Choices struct {
						Type string `json:"type"`
						Items struct {
							Ref string `json:"$ref"`
						} `json:"items"`
					} `json:"choices"`
					Type struct {
						Type string `json:"type"`
						Const int `json:"const"`
					} `json:"type"`
					Name struct {
						Type string `json:"type"`
					} `json:"name"`
					Description struct {
						Type string `json:"type"`
					} `json:"description"`
					Required struct {
						Type string `json:"type"`
					} `json:"required"`
					MinValue struct {
						Type string `json:"type"`
						Description string `json:"description"`
					} `json:"min_value"`
					MaxValue struct {
						Type string `json:"type"`
						Description string `json:"description"`
					} `json:"max_value"`
				} `json:"properties,omitempty"`
			} `json:"anyOf"`
			Deprecated string `json:"deprecated"`
		} `json:"APIApplicationCommandOptionWithAutocompleteOrChoicesWrapper<interface-1910954259-254-736-1910954259-0-13611295383896,APIApplicationCommandOptionChoice<number>>,omitempty"`
		APIApplicationCommandOptionBaseEnum84748279940341184748279904278474827990818 struct {
			Type string `json:"type"`
			Properties struct {
				Type struct {
					Type string `json:"type"`
					Const int `json:"const"`
				} `json:"type"`
				Name struct {
					Type string `json:"type"`
				} `json:"name"`
				Description struct {
					Type string `json:"type"`
				} `json:"description"`
				Required struct {
					Type string `json:"type"`
				} `json:"required"`
			} `json:"properties"`
			Required []string `json:"required"`
			AdditionalProperties bool `json:"additionalProperties"`
			Deprecated string `json:"deprecated"`
		} `json:"APIApplicationCommandOptionBase<enum-847482799-403-411-847482799-0-427-847482799-0-818>,omitempty"`
		APIApplicationCommandInteractionDataNumberOption struct {
			Type string `json:"type"`
			Properties struct {
				Name struct {
					Type string `json:"type"`
				} `json:"name"`
				Type struct {
					Type string `json:"type"`
					Const int `json:"const"`
				} `json:"type"`
				Value struct {
					Type string `json:"type"`
				} `json:"value"`
				Focused struct {
					Type string `json:"type"`
				} `json:"focused"`
			} `json:"properties"`
			AdditionalProperties bool `json:"additionalProperties"`
			Required []string `json:"required"`
			Deprecated string `json:"deprecated"`
		} `json:"APIApplicationCommandInteractionDataNumberOption,omitempty"`
		APIInteractionDataOptionBaseEnum84748279940341184748279904278474827990818Number struct {
			Type string `json:"type"`
			Properties struct {
				Name struct {
					Type string `json:"type"`
				} `json:"name"`
				Type struct {
					Type string `json:"type"`
					Const int `json:"const"`
				} `json:"type"`
				Value struct {
					Type string `json:"type"`
				} `json:"value"`
			} `json:"properties"`
			Required []string `json:"required"`
			AdditionalProperties bool `json:"additionalProperties"`
			Deprecated string `json:"deprecated"`
		} `json:"APIInteractionDataOptionBase<enum-847482799-403-411-847482799-0-427-847482799-0-818,number>,omitempty"`
		APIApplicationCommandRoleOption struct {
			Ref string `json:"$ref"`
			Deprecated string `json:"deprecated"`
		} `json:"APIApplicationCommandRoleOption,omitempty"`
		APIApplicationCommandOptionBaseEnum84748279938238884748279904278474827990818 struct {
			Type string `json:"type"`
			Properties struct {
				Type struct {
					Type string `json:"type"`
					Const int `json:"const"`
				} `json:"type"`
				Name struct {
					Type string `json:"type"`
				} `json:"name"`
				Description struct {
					Type string `json:"type"`
				} `json:"description"`
				Required struct {
					Type string `json:"type"`
				} `json:"required"`
			} `json:"properties"`
			Required []string `json:"required"`
			AdditionalProperties bool `json:"additionalProperties"`
			Deprecated string `json:"deprecated"`
		} `json:"APIApplicationCommandOptionBase<enum-847482799-382-388-847482799-0-427-847482799-0-818>,omitempty"`
		APIApplicationCommandInteractionDataRoleOption struct {
			Ref string `json:"$ref"`
			Deprecated string `json:"deprecated"`
		} `json:"APIApplicationCommandInteractionDataRoleOption,omitempty"`
		APIInteractionDataOptionBaseEnum84748279938238884748279904278474827990818Snowflake struct {
			Type string `json:"type"`
			Properties struct {
				Name struct {
					Type string `json:"type"`
				} `json:"name"`
				Type struct {
					Type string `json:"type"`
					Const int `json:"const"`
				} `json:"type"`
				Value struct {
					Ref string `json:"$ref"`
				} `json:"value"`
			} `json:"properties"`
			Required []string `json:"required"`
			AdditionalProperties bool `json:"additionalProperties"`
			Deprecated string `json:"deprecated"`
		} `json:"APIInteractionDataOptionBase<enum-847482799-382-388-847482799-0-427-847482799-0-818,Snowflake>,omitempty"`
		ApplicationCommandOptionType struct {
			Type string `json:"type"`
			Enum []int `json:"enum"`
			Description string `json:"description"`
			Deprecated string `json:"deprecated"`
		} `json:"ApplicationCommandOptionType,omitempty"`
		APIApplicationCommandStringOption struct {
			Ref string `json:"$ref"`
			Deprecated string `json:"deprecated"`
		} `json:"APIApplicationCommandStringOption,omitempty"`
		APIApplicationCommandOptionWithAutocompleteOrChoicesWrapperAPIApplicationCommandOptionBaseEnum84748279933634484748279904278474827990818APIApplicationCommandOptionChoiceString struct {
			AnyOf []struct {
				Type string `json:"type"`
				AdditionalProperties bool `json:"additionalProperties"`
				Properties struct {
					Autocomplete struct {
						Type string `json:"type"`
						Const bool `json:"const"`
					} `json:"autocomplete"`
					Type struct {
						Type string `json:"type"`
						Const int `json:"const"`
					} `json:"type"`
					Name struct {
						Type string `json:"type"`
					} `json:"name"`
					Description struct {
						Type string `json:"type"`
					} `json:"description"`
					Required struct {
						Type string `json:"type"`
					} `json:"required"`
				} `json:"properties,omitempty"`
				Required []string `json:"required"`
				Properties0 struct {
					Autocomplete struct {
						Type string `json:"type"`
						Const bool `json:"const"`
					} `json:"autocomplete"`
					Choices struct {
						Type string `json:"type"`
						Items struct {
							Ref string `json:"$ref"`
						} `json:"items"`
					} `json:"choices"`
					Type struct {
						Type string `json:"type"`
						Const int `json:"const"`
					} `json:"type"`
					Name struct {
						Type string `json:"type"`
					} `json:"name"`
					Description struct {
						Type string `json:"type"`
					} `json:"description"`
					Required struct {
						Type string `json:"type"`
					} `json:"required"`
				} `json:"properties,omitempty"`
			} `json:"anyOf"`
			Deprecated string `json:"deprecated"`
		} `json:"APIApplicationCommandOptionWithAutocompleteOrChoicesWrapper<APIApplicationCommandOptionBase<enum-847482799-336-344-847482799-0-427-847482799-0-818>,APIApplicationCommandOptionChoice<string>>,omitempty"`
		APIApplicationCommandOptionBaseEnum84748279933634484748279904278474827990818 struct {
			Type string `json:"type"`
			Properties struct {
				Type struct {
					Type string `json:"type"`
					Const int `json:"const"`
				} `json:"type"`
				Name struct {
					Type string `json:"type"`
				} `json:"name"`
				Description struct {
					Type string `json:"type"`
				} `json:"description"`
				Required struct {
					Type string `json:"type"`
				} `json:"required"`
			} `json:"properties"`
			Required []string `json:"required"`
			AdditionalProperties bool `json:"additionalProperties"`
			Deprecated string `json:"deprecated"`
		} `json:"APIApplicationCommandOptionBase<enum-847482799-336-344-847482799-0-427-847482799-0-818>,omitempty"`
		APIApplicationCommandOptionChoiceString struct {
			Type string `json:"type"`
			Properties struct {
				Name struct {
					Type string `json:"type"`
				} `json:"name"`
				Value struct {
					Type string `json:"type"`
				} `json:"value"`
			} `json:"properties"`
			Required []string `json:"required"`
			AdditionalProperties bool `json:"additionalProperties"`
			Description string `json:"description"`
			Deprecated string `json:"deprecated"`
		} `json:"APIApplicationCommandOptionChoice<string>,omitempty"`
		APIApplicationCommandInteractionDataStringOption struct {
			Type string `json:"type"`
			Properties struct {
				Name struct {
					Type string `json:"type"`
				} `json:"name"`
				Type struct {
					Type string `json:"type"`
					Const int `json:"const"`
				} `json:"type"`
				Value struct {
					Type string `json:"type"`
				} `json:"value"`
				Focused struct {
					Type string `json:"type"`
				} `json:"focused"`
			} `json:"properties"`
			AdditionalProperties bool `json:"additionalProperties"`
			Required []string `json:"required"`
			Deprecated string `json:"deprecated"`
		} `json:"APIApplicationCommandInteractionDataStringOption,omitempty"`
		APIInteractionDataOptionBaseEnum84748279933634484748279904278474827990818String struct {
			Type string `json:"type"`
			Properties struct {
				Name struct {
					Type string `json:"type"`
				} `json:"name"`
				Type struct {
					Type string `json:"type"`
					Const int `json:"const"`
				} `json:"type"`
				Value struct {
					Type string `json:"type"`
				} `json:"value"`
			} `json:"properties"`
			Required []string `json:"required"`
			AdditionalProperties bool `json:"additionalProperties"`
			Deprecated string `json:"deprecated"`
		} `json:"APIInteractionDataOptionBase<enum-847482799-336-344-847482799-0-427-847482799-0-818,string>,omitempty"`
		APIApplicationCommandSubcommandOption struct {
			Type string `json:"type"`
			Properties struct {
				Type struct {
					Type string `json:"type"`
					Const int `json:"const"`
				} `json:"type"`
				Name struct {
					Type string `json:"type"`
				} `json:"name"`
				Description struct {
					Type string `json:"type"`
				} `json:"description"`
				Required struct {
					Type string `json:"type"`
				} `json:"required"`
				Options struct {
					Type string `json:"type"`
					Items struct {
						Ref string `json:"$ref"`
					} `json:"items"`
				} `json:"options"`
			} `json:"properties"`
			AdditionalProperties bool `json:"additionalProperties"`
			Required []string `json:"required"`
			Deprecated string `json:"deprecated"`
		} `json:"APIApplicationCommandSubcommandOption,omitempty"`
		APIApplicationCommandOptionBaseEnum84748279930131784748279904278474827990818 struct {
			Type string `json:"type"`
			Properties struct {
				Type struct {
					Type string `json:"type"`
					Const int `json:"const"`
				} `json:"type"`
				Name struct {
					Type string `json:"type"`
				} `json:"name"`
				Description struct {
					Type string `json:"type"`
				} `json:"description"`
				Required struct {
					Type string `json:"type"`
				} `json:"required"`
			} `json:"properties"`
			Required []string `json:"required"`
			AdditionalProperties bool `json:"additionalProperties"`
			Deprecated string `json:"deprecated"`
		} `json:"APIApplicationCommandOptionBase<enum-847482799-301-317-847482799-0-427-847482799-0-818>,omitempty"`
		APIApplicationCommandBasicOption struct {
			AnyOf []struct {
				Ref string `json:"$ref"`
			} `json:"anyOf"`
			Description string `json:"description"`
			Deprecated string `json:"deprecated"`
		} `json:"APIApplicationCommandBasicOption,omitempty"`
		APIApplicationCommandUserOption struct {
			Ref string `json:"$ref"`
			Deprecated string `json:"deprecated"`
		} `json:"APIApplicationCommandUserOption,omitempty"`
		APIApplicationCommandOptionBaseEnum84748279936537184748279904278474827990818 struct {
			Type string `json:"type"`
			Properties struct {
				Type struct {
					Type string `json:"type"`
					Const int `json:"const"`
				} `json:"type"`
				Name struct {
					Type string `json:"type"`
				} `json:"name"`
				Description struct {
					Type string `json:"type"`
				} `json:"description"`
				Required struct {
					Type string `json:"type"`
				} `json:"required"`
			} `json:"properties"`
			Required []string `json:"required"`
			AdditionalProperties bool `json:"additionalProperties"`
			Deprecated string `json:"deprecated"`
		} `json:"APIApplicationCommandOptionBase<enum-847482799-365-371-847482799-0-427-847482799-0-818>,omitempty"`
		APIApplicationCommandInteractionDataSubcommandOption struct {
			Type string `json:"type"`
			Properties struct {
				Name struct {
					Type string `json:"type"`
				} `json:"name"`
				Type struct {
					Type string `json:"type"`
					Const int `json:"const"`
				} `json:"type"`
				Options struct {
					Type string `json:"type"`
					Items struct {
						Ref string `json:"$ref"`
					} `json:"items"`
				} `json:"options"`
			} `json:"properties"`
			Required []string `json:"required"`
			AdditionalProperties bool `json:"additionalProperties"`
			Deprecated string `json:"deprecated"`
		} `json:"APIApplicationCommandInteractionDataSubcommandOption,omitempty"`
		APIApplicationCommandInteractionDataBasicOption struct {
			AnyOf []struct {
				Ref string `json:"$ref"`
			} `json:"anyOf"`
			Deprecated string `json:"deprecated"`
		} `json:"APIApplicationCommandInteractionDataBasicOption,omitempty"`
		APIApplicationCommandInteractionDataUserOption struct {
			Ref string `json:"$ref"`
			Deprecated string `json:"deprecated"`
		} `json:"APIApplicationCommandInteractionDataUserOption,omitempty"`
		APIInteractionDataOptionBaseEnum84748279936537184748279904278474827990818Snowflake struct {
			Type string `json:"type"`
			Properties struct {
				Name struct {
					Type string `json:"type"`
				} `json:"name"`
				Type struct {
					Type string `json:"type"`
					Const int `json:"const"`
				} `json:"type"`
				Value struct {
					Ref string `json:"$ref"`
				} `json:"value"`
			} `json:"properties"`
			Required []string `json:"required"`
			AdditionalProperties bool `json:"additionalProperties"`
			Deprecated string `json:"deprecated"`
		} `json:"APIInteractionDataOptionBase<enum-847482799-365-371-847482799-0-427-847482799-0-818,Snowflake>,omitempty"`
		APIApplicationCommandSubcommandGroupOption struct {
			Type string `json:"type"`
			Properties struct {
				Type struct {
					Type string `json:"type"`
					Const int `json:"const"`
				} `json:"type"`
				Name struct {
					Type string `json:"type"`
				} `json:"name"`
				Description struct {
					Type string `json:"type"`
				} `json:"description"`
				Required struct {
					Type string `json:"type"`
				} `json:"required"`
				Options struct {
					Type string `json:"type"`
					Items struct {
						Ref string `json:"$ref"`
					} `json:"items"`
				} `json:"options"`
			} `json:"properties"`
			AdditionalProperties bool `json:"additionalProperties"`
			Required []string `json:"required"`
			Deprecated string `json:"deprecated"`
		} `json:"APIApplicationCommandSubcommandGroupOption,omitempty"`
		APIApplicationCommandOptionBaseEnum84748279931833584748279904278474827990818 struct {
			Type string `json:"type"`
			Properties struct {
				Type struct {
					Type string `json:"type"`
					Const int `json:"const"`
				} `json:"type"`
				Name struct {
					Type string `json:"type"`
				} `json:"name"`
				Description struct {
					Type string `json:"type"`
				} `json:"description"`
				Required struct {
					Type string `json:"type"`
				} `json:"required"`
			} `json:"properties"`
			Required []string `json:"required"`
			AdditionalProperties bool `json:"additionalProperties"`
			Deprecated string `json:"deprecated"`
		} `json:"APIApplicationCommandOptionBase<enum-847482799-318-335-847482799-0-427-847482799-0-818>,omitempty"`
		APIApplicationCommandInteractionDataSubcommandGroupOption struct {
			Type string `json:"type"`
			Properties struct {
				Name struct {
					Type string `json:"type"`
				} `json:"name"`
				Type struct {
					Type string `json:"type"`
					Const int `json:"const"`
				} `json:"type"`
				Options struct {
					Type string `json:"type"`
					Items struct {
						Ref string `json:"$ref"`
					} `json:"items"`
				} `json:"options"`
			} `json:"properties"`
			Required []string `json:"required"`
			AdditionalProperties bool `json:"additionalProperties"`
			Deprecated string `json:"deprecated"`
		} `json:"APIApplicationCommandInteractionDataSubcommandGroupOption,omitempty"`
	} `json:"definitions"`
}