type AutoGenerated struct {
	Definitions struct {
		APIApplicationCommandStringOption struct {
			Ref string `json:"$ref"`
			Deprecated string `json:"deprecated"`
		} `json:"APIApplicationCommandStringOption"`
		APIApplicationCommandOptionWithAutocompleteOrChoicesWrapperAPIApplicationCommandOptionBaseEnum20937207223363442093720722042720937207220818APIApplicationCommandOptionChoiceString struct {
			AnyOf []struct {
				Type string `json:"type"`
				AdditionalProperties bool `json:"additionalProperties"`
				Properties struct {
					Autocomplete struct {
						Type string `json:"type"`
						Const bool `json:"const"`
					} `json:"autocomplete"`
					Type struct {
						Type string `json:"type"`
						Const int `json:"const"`
					} `json:"type"`
					Name struct {
						Type string `json:"type"`
					} `json:"name"`
					Description struct {
						Type string `json:"type"`
					} `json:"description"`
					Required struct {
						Type string `json:"type"`
					} `json:"required"`
				} `json:"properties,omitempty"`
				Required []string `json:"required"`
				Properties0 struct {
					Autocomplete struct {
						Type string `json:"type"`
						Const bool `json:"const"`
					} `json:"autocomplete"`
					Choices struct {
						Type string `json:"type"`
						Items struct {
							Ref string `json:"$ref"`
						} `json:"items"`
					} `json:"choices"`
					Type struct {
						Type string `json:"type"`
						Const int `json:"const"`
					} `json:"type"`
					Name struct {
						Type string `json:"type"`
					} `json:"name"`
					Description struct {
						Type string `json:"type"`
					} `json:"description"`
					Required struct {
						Type string `json:"type"`
					} `json:"required"`
				} `json:"properties,omitempty"`
			} `json:"anyOf"`
			Deprecated string `json:"deprecated"`
		} `json:"APIApplicationCommandOptionWithAutocompleteOrChoicesWrapper<APIApplicationCommandOptionBase<enum-2093720722-336-344-2093720722-0-427-2093720722-0-818>,APIApplicationCommandOptionChoice<string>>"`
		APIApplicationCommandOptionBaseEnum20937207223363442093720722042720937207220818 struct {
			Type string `json:"type"`
			Properties struct {
				Type struct {
					Type string `json:"type"`
					Const int `json:"const"`
				} `json:"type"`
				Name struct {
					Type string `json:"type"`
				} `json:"name"`
				Description struct {
					Type string `json:"type"`
				} `json:"description"`
				Required struct {
					Type string `json:"type"`
				} `json:"required"`
			} `json:"properties"`
			Required []string `json:"required"`
			AdditionalProperties bool `json:"additionalProperties"`
			Deprecated string `json:"deprecated"`
		} `json:"APIApplicationCommandOptionBase<enum-2093720722-336-344-2093720722-0-427-2093720722-0-818>"`
		APIApplicationCommandOptionChoiceString struct {
			Type string `json:"type"`
			Properties struct {
				Name struct {
					Type string `json:"type"`
				} `json:"name"`
				Value struct {
					Type string `json:"type"`
				} `json:"value"`
			} `json:"properties"`
			Required []string `json:"required"`
			AdditionalProperties bool `json:"additionalProperties"`
			Description string `json:"description"`
			Deprecated string `json:"deprecated"`
		} `json:"APIApplicationCommandOptionChoice<string>"`
		APIApplicationCommandInteractionDataStringOption struct {
			Type string `json:"type"`
			Properties struct {
				Name struct {
					Type string `json:"type"`
				} `json:"name"`
				Type struct {
					Type string `json:"type"`
					Const int `json:"const"`
				} `json:"type"`
				Value struct {
					Type string `json:"type"`
				} `json:"value"`
				Focused struct {
					Type string `json:"type"`
				} `json:"focused"`
			} `json:"properties"`
			AdditionalProperties bool `json:"additionalProperties"`
			Required []string `json:"required"`
			Deprecated string `json:"deprecated"`
		} `json:"APIApplicationCommandInteractionDataStringOption"`
		APIInteractionDataOptionBaseEnum20937207223363442093720722042720937207220818String struct {
			Type string `json:"type"`
			Properties struct {
				Name struct {
					Type string `json:"type"`
				} `json:"name"`
				Type struct {
					Type string `json:"type"`
					Const int `json:"const"`
				} `json:"type"`
				Value struct {
					Type string `json:"type"`
				} `json:"value"`
			} `json:"properties"`
			Required []string `json:"required"`
			AdditionalProperties bool `json:"additionalProperties"`
			Deprecated string `json:"deprecated"`
		} `json:"APIInteractionDataOptionBase<enum-2093720722-336-344-2093720722-0-427-2093720722-0-818,string>"`
	} `json:"definitions"`
}