type AutoGenerated struct {
	Definitions struct {
		APIApplicationCommandUserOption struct {
			Ref string `json:"$ref"`
			Deprecated string `json:"deprecated"`
		} `json:"APIApplicationCommandUserOption"`
		APIApplicationCommandOptionBaseEnum20937207223653712093720722042720937207220818 struct {
			Type string `json:"type"`
			Properties struct {
				Type struct {
					Type string `json:"type"`
					Const int `json:"const"`
				} `json:"type"`
				Name struct {
					Type string `json:"type"`
				} `json:"name"`
				Description struct {
					Type string `json:"type"`
				} `json:"description"`
				Required struct {
					Type string `json:"type"`
				} `json:"required"`
			} `json:"properties"`
			Required []string `json:"required"`
			AdditionalProperties bool `json:"additionalProperties"`
			Deprecated string `json:"deprecated"`
		} `json:"APIApplicationCommandOptionBase<enum-2093720722-365-371-2093720722-0-427-2093720722-0-818>"`
		APIApplicationCommandInteractionDataUserOption struct {
			Ref string `json:"$ref"`
			Deprecated string `json:"deprecated"`
		} `json:"APIApplicationCommandInteractionDataUserOption"`
		APIInteractionDataOptionBaseEnum20937207223653712093720722042720937207220818Snowflake struct {
			Type string `json:"type"`
			Properties struct {
				Name struct {
					Type string `json:"type"`
				} `json:"name"`
				Type struct {
					Type string `json:"type"`
					Const int `json:"const"`
				} `json:"type"`
				Value struct {
					Ref string `json:"$ref"`
				} `json:"value"`
			} `json:"properties"`
			Required []string `json:"required"`
			AdditionalProperties bool `json:"additionalProperties"`
			Deprecated string `json:"deprecated"`
		} `json:"APIInteractionDataOptionBase<enum-2093720722-365-371-2093720722-0-427-2093720722-0-818,Snowflake>"`
		Snowflake struct {
			Type string `json:"type"`
			Description string `json:"description"`
		} `json:"Snowflake"`
	} `json:"definitions"`
}