type AutoGenerated struct {
	Definitions struct {
		APIPartialChannel struct {
			Type string `json:"type"`
			Properties struct {
				ID struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"id"`
				Type struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"type"`
				Name struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"name"`
			} `json:"properties"`
			Required []string `json:"required"`
			AdditionalProperties bool `json:"additionalProperties"`
			Description string `json:"description"`
		} `json:"APIPartialChannel"`
		Snowflake struct {
			Type string `json:"type"`
			Description string `json:"description"`
		} `json:"Snowflake"`
		ChannelType struct {
			Type string `json:"type"`
			Enum []int `json:"enum"`
			Description string `json:"description"`
		} `json:"ChannelType"`
		TextChannelType struct {
			AnyOf []struct {
				Type string `json:"type"`
				Const int `json:"const"`
				Description string `json:"description"`
			} `json:"anyOf"`
		} `json:"TextChannelType"`
		GuildChannelType struct {
			AnyOf []struct {
				Type string `json:"type"`
				Const int `json:"const"`
				Description string `json:"description"`
			} `json:"anyOf"`
		} `json:"GuildChannelType"`
		GuildTextChannelType struct {
			AnyOf []struct {
				Type string `json:"type"`
				Const int `json:"const"`
				Description string `json:"description"`
			} `json:"anyOf"`
		} `json:"GuildTextChannelType"`
		APITextChannel struct {
			Type string `json:"type"`
			Properties struct {
				ID struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"id"`
				Type struct {
					Type string `json:"type"`
					Const int `json:"const"`
					Description string `json:"description"`
				} `json:"type"`
				Name struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"name"`
				GuildID struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"guild_id"`
				PermissionOverwrites struct {
					Type string `json:"type"`
					Items struct {
						Ref string `json:"$ref"`
					} `json:"items"`
					Description string `json:"description"`
				} `json:"permission_overwrites"`
				Position struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"position"`
				ParentID struct {
					AnyOf []struct {
						Ref string `json:"$ref,omitempty"`
						Type string `json:"type,omitempty"`
					} `json:"anyOf"`
					Description string `json:"description"`
				} `json:"parent_id"`
				Nsfw struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"nsfw"`
				LastMessageID struct {
					AnyOf []struct {
						Ref string `json:"$ref,omitempty"`
						Type string `json:"type,omitempty"`
					} `json:"anyOf"`
					Description string `json:"description"`
				} `json:"last_message_id"`
				DefaultAutoArchiveDuration struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"default_auto_archive_duration"`
				Topic struct {
					Type []string `json:"type"`
					Description string `json:"description"`
				} `json:"topic"`
				LastPinTimestamp struct {
					Type []string `json:"type"`
					Description string `json:"description"`
				} `json:"last_pin_timestamp"`
				RateLimitPerUser struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"rate_limit_per_user"`
			} `json:"properties"`
			AdditionalProperties bool `json:"additionalProperties"`
			Required []string `json:"required"`
		} `json:"APITextChannel"`
		APIGuildTextChannelEnum1354526010757976341354526010745887621354526010033636732917173 struct {
			Type string `json:"type"`
			Properties struct {
				ID struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"id"`
				Type struct {
					Type string `json:"type"`
					Const int `json:"const"`
					Description string `json:"description"`
				} `json:"type"`
				Name struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"name"`
				GuildID struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"guild_id"`
				PermissionOverwrites struct {
					Type string `json:"type"`
					Items struct {
						Ref string `json:"$ref"`
					} `json:"items"`
					Description string `json:"description"`
				} `json:"permission_overwrites"`
				Position struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"position"`
				ParentID struct {
					AnyOf []struct {
						Ref string `json:"$ref,omitempty"`
						Type string `json:"type,omitempty"`
					} `json:"anyOf"`
					Description string `json:"description"`
				} `json:"parent_id"`
				Nsfw struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"nsfw"`
				LastMessageID struct {
					AnyOf []struct {
						Ref string `json:"$ref,omitempty"`
						Type string `json:"type,omitempty"`
					} `json:"anyOf"`
					Description string `json:"description"`
				} `json:"last_message_id"`
				DefaultAutoArchiveDuration struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"default_auto_archive_duration"`
				Topic struct {
					Type []string `json:"type"`
					Description string `json:"description"`
				} `json:"topic"`
				LastPinTimestamp struct {
					Type []string `json:"type"`
					Description string `json:"description"`
				} `json:"last_pin_timestamp"`
			} `json:"properties"`
			AdditionalProperties bool `json:"additionalProperties"`
			Required []string `json:"required"`
		} `json:"APIGuildTextChannel<enum-1354526010-7579-7634-1354526010-7458-8762-1354526010-0-33636732917173>"`
		APITextBasedChannelEnum1354526010757976341354526010745887621354526010033636732917173 struct {
			Type string `json:"type"`
			Properties struct {
				ID struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"id"`
				Type struct {
					Type string `json:"type"`
					Const int `json:"const"`
					Description string `json:"description"`
				} `json:"type"`
				Name struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"name"`
				LastMessageID struct {
					AnyOf []struct {
						Ref string `json:"$ref,omitempty"`
						Type string `json:"type,omitempty"`
					} `json:"anyOf"`
					Description string `json:"description"`
				} `json:"last_message_id"`
			} `json:"properties"`
			AdditionalProperties bool `json:"additionalProperties"`
			Required []string `json:"required"`
		} `json:"APITextBasedChannel<enum-1354526010-7579-7634-1354526010-7458-8762-1354526010-0-33636732917173>"`
		APIChannelBaseEnum1354526010757976341354526010745887621354526010033636732917173 struct {
			Type string `json:"type"`
			Properties struct {
				ID struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"id"`
				Type struct {
					Type string `json:"type"`
					Const int `json:"const"`
					Description string `json:"description"`
				} `json:"type"`
				Name struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"name"`
			} `json:"properties"`
			Required []string `json:"required"`
			AdditionalProperties bool `json:"additionalProperties"`
			Description string `json:"description"`
		} `json:"APIChannelBase<enum-1354526010-7579-7634-1354526010-7458-8762-1354526010-0-33636732917173>"`
		APIGuildChannelEnum1354526010757976341354526010745887621354526010033636732917173 struct {
			Type string `json:"type"`
			Properties struct {
				ID struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"id"`
				Type struct {
					Type string `json:"type"`
					Const int `json:"const"`
					Description string `json:"description"`
				} `json:"type"`
				Name struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"name"`
				GuildID struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"guild_id"`
				PermissionOverwrites struct {
					Type string `json:"type"`
					Items struct {
						Ref string `json:"$ref"`
					} `json:"items"`
					Description string `json:"description"`
				} `json:"permission_overwrites"`
				Position struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"position"`
				ParentID struct {
					AnyOf []struct {
						Ref string `json:"$ref,omitempty"`
						Type string `json:"type,omitempty"`
					} `json:"anyOf"`
					Description string `json:"description"`
				} `json:"parent_id"`
				Nsfw struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"nsfw"`
			} `json:"properties"`
			AdditionalProperties bool `json:"additionalProperties"`
			Required []string `json:"required"`
		} `json:"APIGuildChannel<enum-1354526010-7579-7634-1354526010-7458-8762-1354526010-0-33636732917173>"`
		APIOverwrite struct {
			Type string `json:"type"`
			Properties struct {
				ID struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"id"`
				Type struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"type"`
				Allow struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"allow"`
				Deny struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"deny"`
			} `json:"properties"`
			Required []string `json:"required"`
			AdditionalProperties bool `json:"additionalProperties"`
			Description string `json:"description"`
		} `json:"APIOverwrite"`
		OverwriteType struct {
			Type string `json:"type"`
			Enum []int `json:"enum"`
		} `json:"OverwriteType"`
		ThreadAutoArchiveDuration struct {
			Type string `json:"type"`
			Enum []int `json:"enum"`
		} `json:"ThreadAutoArchiveDuration"`
		APINewsChannel struct {
			Ref string `json:"$ref"`
		} `json:"APINewsChannel"`
		APIGuildTextChannelEnum13545260107990815313545260107458876213545260100336361915191889 struct {
			Type string `json:"type"`
			Properties struct {
				ID struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"id"`
				Type struct {
					Type string `json:"type"`
					Const int `json:"const"`
					Description string `json:"description"`
				} `json:"type"`
				Name struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"name"`
				GuildID struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"guild_id"`
				PermissionOverwrites struct {
					Type string `json:"type"`
					Items struct {
						Ref string `json:"$ref"`
					} `json:"items"`
					Description string `json:"description"`
				} `json:"permission_overwrites"`
				Position struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"position"`
				ParentID struct {
					AnyOf []struct {
						Ref string `json:"$ref,omitempty"`
						Type string `json:"type,omitempty"`
					} `json:"anyOf"`
					Description string `json:"description"`
				} `json:"parent_id"`
				Nsfw struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"nsfw"`
				LastMessageID struct {
					AnyOf []struct {
						Ref string `json:"$ref,omitempty"`
						Type string `json:"type,omitempty"`
					} `json:"anyOf"`
					Description string `json:"description"`
				} `json:"last_message_id"`
				DefaultAutoArchiveDuration struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"default_auto_archive_duration"`
				Topic struct {
					Type []string `json:"type"`
					Description string `json:"description"`
				} `json:"topic"`
				LastPinTimestamp struct {
					Type []string `json:"type"`
					Description string `json:"description"`
				} `json:"last_pin_timestamp"`
			} `json:"properties"`
			AdditionalProperties bool `json:"additionalProperties"`
			Required []string `json:"required"`
		} `json:"APIGuildTextChannel<enum-1354526010-7990-8153-1354526010-7458-8762-1354526010-0-336361915191889>"`
		APITextBasedChannelEnum13545260107990815313545260107458876213545260100336361915191889 struct {
			Type string `json:"type"`
			Properties struct {
				ID struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"id"`
				Type struct {
					Type string `json:"type"`
					Const int `json:"const"`
					Description string `json:"description"`
				} `json:"type"`
				Name struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"name"`
				LastMessageID struct {
					AnyOf []struct {
						Ref string `json:"$ref,omitempty"`
						Type string `json:"type,omitempty"`
					} `json:"anyOf"`
					Description string `json:"description"`
				} `json:"last_message_id"`
			} `json:"properties"`
			AdditionalProperties bool `json:"additionalProperties"`
			Required []string `json:"required"`
		} `json:"APITextBasedChannel<enum-1354526010-7990-8153-1354526010-7458-8762-1354526010-0-336361915191889>"`
		APIChannelBaseEnum13545260107990815313545260107458876213545260100336361915191889 struct {
			Type string `json:"type"`
			Properties struct {
				ID struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"id"`
				Type struct {
					Type string `json:"type"`
					Const int `json:"const"`
					Description string `json:"description"`
				} `json:"type"`
				Name struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"name"`
			} `json:"properties"`
			Required []string `json:"required"`
			AdditionalProperties bool `json:"additionalProperties"`
			Description string `json:"description"`
		} `json:"APIChannelBase<enum-1354526010-7990-8153-1354526010-7458-8762-1354526010-0-336361915191889>"`
		APIGuildChannelEnum13545260107990815313545260107458876213545260100336361915191889 struct {
			Type string `json:"type"`
			Properties struct {
				ID struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"id"`
				Type struct {
					Type string `json:"type"`
					Const int `json:"const"`
					Description string `json:"description"`
				} `json:"type"`
				Name struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"name"`
				GuildID struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"guild_id"`
				PermissionOverwrites struct {
					Type string `json:"type"`
					Items struct {
						Ref string `json:"$ref"`
					} `json:"items"`
					Description string `json:"description"`
				} `json:"permission_overwrites"`
				Position struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"position"`
				ParentID struct {
					AnyOf []struct {
						Ref string `json:"$ref,omitempty"`
						Type string `json:"type,omitempty"`
					} `json:"anyOf"`
					Description string `json:"description"`
				} `json:"parent_id"`
				Nsfw struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"nsfw"`
			} `json:"properties"`
			AdditionalProperties bool `json:"additionalProperties"`
			Required []string `json:"required"`
		} `json:"APIGuildChannel<enum-1354526010-7990-8153-1354526010-7458-8762-1354526010-0-336361915191889>"`
		APIGuildCategoryChannel struct {
			Ref string `json:"$ref"`
		} `json:"APIGuildCategoryChannel"`
		APIGuildChannelEnum13545260107807798913545260107458876213545260100336361025724393 struct {
			Type string `json:"type"`
			Properties struct {
				ID struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"id"`
				Type struct {
					Type string `json:"type"`
					Const int `json:"const"`
					Description string `json:"description"`
				} `json:"type"`
				Name struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"name"`
				GuildID struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"guild_id"`
				PermissionOverwrites struct {
					Type string `json:"type"`
					Items struct {
						Ref string `json:"$ref"`
					} `json:"items"`
					Description string `json:"description"`
				} `json:"permission_overwrites"`
				Position struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"position"`
				ParentID struct {
					AnyOf []struct {
						Ref string `json:"$ref,omitempty"`
						Type string `json:"type,omitempty"`
					} `json:"anyOf"`
					Description string `json:"description"`
				} `json:"parent_id"`
				Nsfw struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"nsfw"`
			} `json:"properties"`
			AdditionalProperties bool `json:"additionalProperties"`
			Required []string `json:"required"`
		} `json:"APIGuildChannel<enum-1354526010-7807-7989-1354526010-7458-8762-1354526010-0-336361025724393>"`
		APIChannelBaseEnum13545260107807798913545260107458876213545260100336361025724393 struct {
			Type string `json:"type"`
			Properties struct {
				ID struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"id"`
				Type struct {
					Type string `json:"type"`
					Const int `json:"const"`
					Description string `json:"description"`
				} `json:"type"`
				Name struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"name"`
			} `json:"properties"`
			Required []string `json:"required"`
			AdditionalProperties bool `json:"additionalProperties"`
			Description string `json:"description"`
		} `json:"APIChannelBase<enum-1354526010-7807-7989-1354526010-7458-8762-1354526010-0-336361025724393>"`
		APIGuildStoreChannel struct {
			Ref string `json:"$ref"`
		} `json:"APIGuildStoreChannel"`
		APIGuildChannelEnum1354526010815483381354526010745887621354526010033636138797936 struct {
			Type string `json:"type"`
			Properties struct {
				ID struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"id"`
				Type struct {
					Type string `json:"type"`
					Const int `json:"const"`
					Description string `json:"description"`
				} `json:"type"`
				Name struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"name"`
				GuildID struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"guild_id"`
				PermissionOverwrites struct {
					Type string `json:"type"`
					Items struct {
						Ref string `json:"$ref"`
					} `json:"items"`
					Description string `json:"description"`
				} `json:"permission_overwrites"`
				Position struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"position"`
				ParentID struct {
					AnyOf []struct {
						Ref string `json:"$ref,omitempty"`
						Type string `json:"type,omitempty"`
					} `json:"anyOf"`
					Description string `json:"description"`
				} `json:"parent_id"`
				Nsfw struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"nsfw"`
			} `json:"properties"`
			AdditionalProperties bool `json:"additionalProperties"`
			Required []string `json:"required"`
		} `json:"APIGuildChannel<enum-1354526010-8154-8338-1354526010-7458-8762-1354526010-0-33636138797936>"`
		APIChannelBaseEnum1354526010815483381354526010745887621354526010033636138797936 struct {
			Type string `json:"type"`
			Properties struct {
				ID struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"id"`
				Type struct {
					Type string `json:"type"`
					Const int `json:"const"`
					Description string `json:"description"`
				} `json:"type"`
				Name struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"name"`
			} `json:"properties"`
			Required []string `json:"required"`
			AdditionalProperties bool `json:"additionalProperties"`
			Description string `json:"description"`
		} `json:"APIChannelBase<enum-1354526010-8154-8338-1354526010-7458-8762-1354526010-0-33636138797936>"`
		APIVoiceChannel struct {
			Type string `json:"type"`
			Properties struct {
				ID struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"id"`
				Type struct {
					AnyOf []struct {
						Type string `json:"type"`
						Const int `json:"const"`
						Description string `json:"description"`
					} `json:"anyOf"`
					Description string `json:"description"`
				} `json:"type"`
				Name struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"name"`
				GuildID struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"guild_id"`
				PermissionOverwrites struct {
					Type string `json:"type"`
					Items struct {
						Ref string `json:"$ref"`
					} `json:"items"`
					Description string `json:"description"`
				} `json:"permission_overwrites"`
				Position struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"position"`
				ParentID struct {
					AnyOf []struct {
						Ref string `json:"$ref,omitempty"`
						Type string `json:"type,omitempty"`
					} `json:"anyOf"`
					Description string `json:"description"`
				} `json:"parent_id"`
				Nsfw struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"nsfw"`
				Bitrate struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"bitrate"`
				UserLimit struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"user_limit"`
				RtcRegion struct {
					Type []string `json:"type"`
					Description string `json:"description"`
				} `json:"rtc_region"`
				VideoQualityMode struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"video_quality_mode"`
			} `json:"properties"`
			AdditionalProperties bool `json:"additionalProperties"`
			Required []string `json:"required"`
		} `json:"APIVoiceChannel"`
		APIGuildChannelEnum13545260108604875913545260107458876213545260100336361830896565Enum1354526010768577421354526010745887621354526010033636121029024 struct {
			Type string `json:"type"`
			Properties struct {
				ID struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"id"`
				Type struct {
					AnyOf []struct {
						Type string `json:"type"`
						Const int `json:"const"`
						Description string `json:"description"`
					} `json:"anyOf"`
					Description string `json:"description"`
				} `json:"type"`
				Name struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"name"`
				GuildID struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"guild_id"`
				PermissionOverwrites struct {
					Type string `json:"type"`
					Items struct {
						Ref string `json:"$ref"`
					} `json:"items"`
					Description string `json:"description"`
				} `json:"permission_overwrites"`
				Position struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"position"`
				ParentID struct {
					AnyOf []struct {
						Ref string `json:"$ref,omitempty"`
						Type string `json:"type,omitempty"`
					} `json:"anyOf"`
					Description string `json:"description"`
				} `json:"parent_id"`
				Nsfw struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"nsfw"`
			} `json:"properties"`
			AdditionalProperties bool `json:"additionalProperties"`
			Required []string `json:"required"`
		} `json:"APIGuildChannel<(enum-1354526010-8604-8759-1354526010-7458-8762-1354526010-0-336361830896565|enum-1354526010-7685-7742-1354526010-7458-8762-1354526010-0-33636121029024)>"`
		APIChannelBaseEnum13545260108604875913545260107458876213545260100336361830896565Enum1354526010768577421354526010745887621354526010033636121029024 struct {
			Type string `json:"type"`
			Properties struct {
				ID struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"id"`
				Type struct {
					AnyOf []struct {
						Type string `json:"type"`
						Const int `json:"const"`
						Description string `json:"description"`
					} `json:"anyOf"`
					Description string `json:"description"`
				} `json:"type"`
				Name struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"name"`
			} `json:"properties"`
			Required []string `json:"required"`
			AdditionalProperties bool `json:"additionalProperties"`
			Description string `json:"description"`
		} `json:"APIChannelBase<(enum-1354526010-8604-8759-1354526010-7458-8762-1354526010-0-336361830896565|enum-1354526010-7685-7742-1354526010-7458-8762-1354526010-0-33636121029024)>"`
		VideoQualityMode struct {
			Type string `json:"type"`
			Enum []int `json:"enum"`
		} `json:"VideoQualityMode"`
		APIDMChannel struct {
			Type string `json:"type"`
			Properties struct {
				ID struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"id"`
				Type struct {
					Type string `json:"type"`
					Const int `json:"const"`
					Description string `json:"description"`
				} `json:"type"`
				Name struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"name"`
				LastMessageID struct {
					AnyOf []struct {
						Ref string `json:"$ref,omitempty"`
						Type string `json:"type,omitempty"`
					} `json:"anyOf"`
					Description string `json:"description"`
				} `json:"last_message_id"`
				Recipients struct {
					Type string `json:"type"`
					Items struct {
						Ref string `json:"$ref"`
					} `json:"items"`
					Description string `json:"description"`
				} `json:"recipients"`
			} `json:"properties"`
			AdditionalProperties bool `json:"additionalProperties"`
			Required []string `json:"required"`
		} `json:"APIDMChannel"`
		APITextBasedChannelEnum1354526010763576841354526010745887621354526010033636102715350 struct {
			Type string `json:"type"`
			Properties struct {
				ID struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"id"`
				Type struct {
					Type string `json:"type"`
					Const int `json:"const"`
					Description string `json:"description"`
				} `json:"type"`
				Name struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"name"`
				LastMessageID struct {
					AnyOf []struct {
						Ref string `json:"$ref,omitempty"`
						Type string `json:"type,omitempty"`
					} `json:"anyOf"`
					Description string `json:"description"`
				} `json:"last_message_id"`
			} `json:"properties"`
			AdditionalProperties bool `json:"additionalProperties"`
			Required []string `json:"required"`
		} `json:"APITextBasedChannel<enum-1354526010-7635-7684-1354526010-7458-8762-1354526010-0-33636102715350>"`
		APIChannelBaseEnum1354526010763576841354526010745887621354526010033636102715350 struct {
			Type string `json:"type"`
			Properties struct {
				ID struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"id"`
				Type struct {
					Type string `json:"type"`
					Const int `json:"const"`
					Description string `json:"description"`
				} `json:"type"`
				Name struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"name"`
			} `json:"properties"`
			Required []string `json:"required"`
			AdditionalProperties bool `json:"additionalProperties"`
			Description string `json:"description"`
		} `json:"APIChannelBase<enum-1354526010-7635-7684-1354526010-7458-8762-1354526010-0-33636102715350>"`
		APIUser struct {
			Type string `json:"type"`
			Properties struct {
				ID struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"id"`
				Username struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"username"`
				Discriminator struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"discriminator"`
				Avatar struct {
					Type []string `json:"type"`
					Description string `json:"description"`
				} `json:"avatar"`
				Bot struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"bot"`
				System struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"system"`
				MfaEnabled struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"mfa_enabled"`
				Banner struct {
					Type []string `json:"type"`
					Description string `json:"description"`
				} `json:"banner"`
				AccentColor struct {
					Type []string `json:"type"`
					Description string `json:"description"`
				} `json:"accent_color"`
				Locale struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"locale"`
				Verified struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"verified"`
				Email struct {
					Type []string `json:"type"`
					Description string `json:"description"`
				} `json:"email"`
				Flags struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"flags"`
				PremiumType struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"premium_type"`
				PublicFlags struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"public_flags"`
			} `json:"properties"`
			Required []string `json:"required"`
			AdditionalProperties bool `json:"additionalProperties"`
			Description string `json:"description"`
		} `json:"APIUser"`
		UserFlags struct {
			Type string `json:"type"`
			Enum []int `json:"enum"`
			Description string `json:"description"`
		} `json:"UserFlags"`
		UserPremiumType struct {
			Type string `json:"type"`
			Enum []int `json:"enum"`
			Description string `json:"description"`
		} `json:"UserPremiumType"`
		APIGroupDMChannel struct {
			Type string `json:"type"`
			Properties struct {
				ID struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"id"`
				Type struct {
					Type string `json:"type"`
					Const int `json:"const"`
					Description string `json:"description"`
				} `json:"type"`
				Name struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"name"`
				LastMessageID struct {
					AnyOf []struct {
						Ref string `json:"$ref,omitempty"`
						Type string `json:"type,omitempty"`
					} `json:"anyOf"`
					Description string `json:"description"`
				} `json:"last_message_id"`
				Recipients struct {
					Type string `json:"type"`
					Items struct {
						Ref string `json:"$ref"`
					} `json:"items"`
					Description string `json:"description"`
				} `json:"recipients"`
				ApplicationID struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"application_id"`
				Icon struct {
					Type []string `json:"type"`
					Description string `json:"description"`
				} `json:"icon"`
				OwnerID struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"owner_id"`
			} `json:"properties"`
			AdditionalProperties bool `json:"additionalProperties"`
			Required []string `json:"required"`
		} `json:"APIGroupDMChannel"`
		APITextBasedChannelEnum13545260107743780613545260107458876213545260100336361767421466 struct {
			Type string `json:"type"`
			Properties struct {
				ID struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"id"`
				Type struct {
					Type string `json:"type"`
					Const int `json:"const"`
					Description string `json:"description"`
				} `json:"type"`
				Name struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"name"`
				LastMessageID struct {
					AnyOf []struct {
						Ref string `json:"$ref,omitempty"`
						Type string `json:"type,omitempty"`
					} `json:"anyOf"`
					Description string `json:"description"`
				} `json:"last_message_id"`
			} `json:"properties"`
			AdditionalProperties bool `json:"additionalProperties"`
			Required []string `json:"required"`
		} `json:"APITextBasedChannel<enum-1354526010-7743-7806-1354526010-7458-8762-1354526010-0-336361767421466>"`
		APIChannelBaseEnum13545260107743780613545260107458876213545260100336361767421466 struct {
			Type string `json:"type"`
			Properties struct {
				ID struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"id"`
				Type struct {
					Type string `json:"type"`
					Const int `json:"const"`
					Description string `json:"description"`
				} `json:"type"`
				Name struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"name"`
			} `json:"properties"`
			Required []string `json:"required"`
			AdditionalProperties bool `json:"additionalProperties"`
			Description string `json:"description"`
		} `json:"APIChannelBase<enum-1354526010-7743-7806-1354526010-7458-8762-1354526010-0-336361767421466>"`
		APIThreadChannel struct {
			Type string `json:"type"`
			Properties struct {
				ID struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"id"`
				Type struct {
					AnyOf []struct {
						Type string `json:"type"`
						Const int `json:"const"`
						Description string `json:"description"`
					} `json:"anyOf"`
					Description string `json:"description"`
				} `json:"type"`
				Name struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"name"`
				GuildID struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"guild_id"`
				PermissionOverwrites struct {
					Type string `json:"type"`
					Items struct {
						Ref string `json:"$ref"`
					} `json:"items"`
					Description string `json:"description"`
				} `json:"permission_overwrites"`
				Position struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"position"`
				ParentID struct {
					AnyOf []struct {
						Ref string `json:"$ref,omitempty"`
						Type string `json:"type,omitempty"`
					} `json:"anyOf"`
					Description string `json:"description"`
				} `json:"parent_id"`
				Nsfw struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"nsfw"`
				Member struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"member"`
				ThreadMetadata struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"thread_metadata"`
				MessageCount struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"message_count"`
				MemberCount struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"member_count"`
				RateLimitPerUser struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"rate_limit_per_user"`
				OwnerID struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"owner_id"`
				LastMessageID struct {
					AnyOf []struct {
						Ref string `json:"$ref,omitempty"`
						Type string `json:"type,omitempty"`
					} `json:"anyOf"`
					Description string `json:"description"`
				} `json:"last_message_id"`
			} `json:"properties"`
			AdditionalProperties bool `json:"additionalProperties"`
			Required []string `json:"required"`
		} `json:"APIThreadChannel"`
		APIGuildChannelEnum1354526010843085151354526010745887621354526010033636612297701Enum13545260108516860313545260107458876213545260100336361507172815Enum13545260108339842913545260107458876213545260100336361372201880 struct {
			Type string `json:"type"`
			Properties struct {
				ID struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"id"`
				Type struct {
					AnyOf []struct {
						Type string `json:"type"`
						Const int `json:"const"`
						Description string `json:"description"`
					} `json:"anyOf"`
					Description string `json:"description"`
				} `json:"type"`
				Name struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"name"`
				GuildID struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"guild_id"`
				PermissionOverwrites struct {
					Type string `json:"type"`
					Items struct {
						Ref string `json:"$ref"`
					} `json:"items"`
					Description string `json:"description"`
				} `json:"permission_overwrites"`
				Position struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"position"`
				ParentID struct {
					AnyOf []struct {
						Ref string `json:"$ref,omitempty"`
						Type string `json:"type,omitempty"`
					} `json:"anyOf"`
					Description string `json:"description"`
				} `json:"parent_id"`
				Nsfw struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"nsfw"`
			} `json:"properties"`
			AdditionalProperties bool `json:"additionalProperties"`
			Required []string `json:"required"`
		} `json:"APIGuildChannel<(enum-1354526010-8430-8515-1354526010-7458-8762-1354526010-0-33636612297701|enum-1354526010-8516-8603-1354526010-7458-8762-1354526010-0-336361507172815|enum-1354526010-8339-8429-1354526010-7458-8762-1354526010-0-336361372201880)>"`
		APIChannelBaseEnum1354526010843085151354526010745887621354526010033636612297701Enum13545260108516860313545260107458876213545260100336361507172815Enum13545260108339842913545260107458876213545260100336361372201880 struct {
			Type string `json:"type"`
			Properties struct {
				ID struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"id"`
				Type struct {
					AnyOf []struct {
						Type string `json:"type"`
						Const int `json:"const"`
						Description string `json:"description"`
					} `json:"anyOf"`
					Description string `json:"description"`
				} `json:"type"`
				Name struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"name"`
			} `json:"properties"`
			Required []string `json:"required"`
			AdditionalProperties bool `json:"additionalProperties"`
			Description string `json:"description"`
		} `json:"APIChannelBase<(enum-1354526010-8430-8515-1354526010-7458-8762-1354526010-0-33636612297701|enum-1354526010-8516-8603-1354526010-7458-8762-1354526010-0-336361507172815|enum-1354526010-8339-8429-1354526010-7458-8762-1354526010-0-336361372201880)>"`
		APIThreadMember struct {
			Type string `json:"type"`
			Properties struct {
				ID struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"id"`
				UserID struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"user_id"`
				JoinTimestamp struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"join_timestamp"`
				Flags struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"flags"`
			} `json:"properties"`
			Required []string `json:"required"`
			AdditionalProperties bool `json:"additionalProperties"`
			Description string `json:"description"`
		} `json:"APIThreadMember"`
		ThreadMemberFlags struct {
			Type []interface{} `json:"type"`
			Enum []interface{} `json:"enum"`
		} `json:"ThreadMemberFlags"`
		APIThreadMetadata struct {
			Type string `json:"type"`
			Properties struct {
				Archived struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"archived"`
				AutoArchiveDuration struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"auto_archive_duration"`
				ArchiveTimestamp struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"archive_timestamp"`
				Locked struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"locked"`
				Invitable struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"invitable"`
				CreateTimestamp struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"create_timestamp"`
			} `json:"properties"`
			Required []string `json:"required"`
			AdditionalProperties bool `json:"additionalProperties"`
			Description string `json:"description"`
		} `json:"APIThreadMetadata"`
		APIChannel struct {
			AnyOf []struct {
				Ref string `json:"$ref"`
			} `json:"anyOf"`
			Description string `json:"description"`
		} `json:"APIChannel"`
		APIMessage struct {
			Type string `json:"type"`
			Properties struct {
				ID struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"id"`
				ChannelID struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"channel_id"`
				GuildID struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"guild_id"`
				Author struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"author"`
				Member struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"member"`
				Content struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"content"`
				Timestamp struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"timestamp"`
				EditedTimestamp struct {
					Type []string `json:"type"`
					Description string `json:"description"`
				} `json:"edited_timestamp"`
				Tts struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"tts"`
				MentionEveryone struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"mention_everyone"`
				Mentions struct {
					Type string `json:"type"`
					Items struct {
						Type string `json:"type"`
						AdditionalProperties bool `json:"additionalProperties"`
						Properties struct {
							Member struct {
								Type string `json:"type"`
								Properties struct {
									Nick struct {
										Type []string `json:"type"`
										Description string `json:"description"`
									} `json:"nick"`
									Avatar struct {
										Type []string `json:"type"`
										Description string `json:"description"`
									} `json:"avatar"`
									Roles struct {
										Type string `json:"type"`
										Items struct {
											Ref string `json:"$ref"`
										} `json:"items"`
										Description string `json:"description"`
									} `json:"roles"`
									JoinedAt struct {
										Type string `json:"type"`
										Description string `json:"description"`
									} `json:"joined_at"`
									PremiumSince struct {
										Type []string `json:"type"`
										Description string `json:"description"`
									} `json:"premium_since"`
									Deaf struct {
										Type string `json:"type"`
										Description string `json:"description"`
									} `json:"deaf"`
									Mute struct {
										Type string `json:"type"`
										Description string `json:"description"`
									} `json:"mute"`
									Pending struct {
										Type string `json:"type"`
										Description string `json:"description"`
									} `json:"pending"`
									CommunicationDisabledUntil struct {
										Type []string `json:"type"`
										Description string `json:"description"`
									} `json:"communication_disabled_until"`
								} `json:"properties"`
								Required []string `json:"required"`
								AdditionalProperties bool `json:"additionalProperties"`
							} `json:"member"`
							ID struct {
								Ref string `json:"$ref"`
								Description string `json:"description"`
							} `json:"id"`
							Username struct {
								Type string `json:"type"`
								Description string `json:"description"`
							} `json:"username"`
							Discriminator struct {
								Type string `json:"type"`
								Description string `json:"description"`
							} `json:"discriminator"`
							Avatar struct {
								Type []string `json:"type"`
								Description string `json:"description"`
							} `json:"avatar"`
							Bot struct {
								Type string `json:"type"`
								Description string `json:"description"`
							} `json:"bot"`
							System struct {
								Type string `json:"type"`
								Description string `json:"description"`
							} `json:"system"`
							MfaEnabled struct {
								Type string `json:"type"`
								Description string `json:"description"`
							} `json:"mfa_enabled"`
							Banner struct {
								Type []string `json:"type"`
								Description string `json:"description"`
							} `json:"banner"`
							AccentColor struct {
								Type []string `json:"type"`
								Description string `json:"description"`
							} `json:"accent_color"`
							Locale struct {
								Type string `json:"type"`
								Description string `json:"description"`
							} `json:"locale"`
							Verified struct {
								Type string `json:"type"`
								Description string `json:"description"`
							} `json:"verified"`
							Email struct {
								Type []string `json:"type"`
								Description string `json:"description"`
							} `json:"email"`
							Flags struct {
								Ref string `json:"$ref"`
								Description string `json:"description"`
							} `json:"flags"`
							PremiumType struct {
								Ref string `json:"$ref"`
								Description string `json:"description"`
							} `json:"premium_type"`
							PublicFlags struct {
								Ref string `json:"$ref"`
								Description string `json:"description"`
							} `json:"public_flags"`
						} `json:"properties"`
						Required []string `json:"required"`
					} `json:"items"`
					Description string `json:"description"`
				} `json:"mentions"`
				MentionRoles struct {
					Type string `json:"type"`
					Items struct {
						Ref string `json:"$ref"`
						Description string `json:"description"`
					} `json:"items"`
					Description string `json:"description"`
				} `json:"mention_roles"`
				MentionChannels struct {
					Type string `json:"type"`
					Items struct {
						Ref string `json:"$ref"`
					} `json:"items"`
					Description string `json:"description"`
				} `json:"mention_channels"`
				Attachments struct {
					Type string `json:"type"`
					Items struct {
						Ref string `json:"$ref"`
					} `json:"items"`
					Description string `json:"description"`
				} `json:"attachments"`
				Embeds struct {
					Type string `json:"type"`
					Items struct {
						Ref string `json:"$ref"`
					} `json:"items"`
					Description string `json:"description"`
				} `json:"embeds"`
				Reactions struct {
					Type string `json:"type"`
					Items struct {
						Ref string `json:"$ref"`
					} `json:"items"`
					Description string `json:"description"`
				} `json:"reactions"`
				Nonce struct {
					Type []string `json:"type"`
					Description string `json:"description"`
				} `json:"nonce"`
				Pinned struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"pinned"`
				WebhookID struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"webhook_id"`
				Type struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"type"`
				Activity struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"activity"`
				Application struct {
					Type string `json:"type"`
					Properties struct {
						ID struct {
							Ref string `json:"$ref"`
							Description string `json:"description"`
						} `json:"id"`
						Name struct {
							Type string `json:"type"`
							Description string `json:"description"`
						} `json:"name"`
						Icon struct {
							Type []string `json:"type"`
							Description string `json:"description"`
						} `json:"icon"`
						Description struct {
							Type string `json:"type"`
							Description string `json:"description"`
						} `json:"description"`
						RPCOrigins struct {
							Type string `json:"type"`
							Items struct {
								Type string `json:"type"`
							} `json:"items"`
							Description string `json:"description"`
						} `json:"rpc_origins"`
						BotPublic struct {
							Type string `json:"type"`
							Description string `json:"description"`
						} `json:"bot_public"`
						BotRequireCodeGrant struct {
							Type string `json:"type"`
							Description string `json:"description"`
						} `json:"bot_require_code_grant"`
						TermsOfServiceURL struct {
							Type string `json:"type"`
							Description string `json:"description"`
						} `json:"terms_of_service_url"`
						PrivacyPolicyURL struct {
							Type string `json:"type"`
							Description string `json:"description"`
						} `json:"privacy_policy_url"`
						Owner struct {
							Ref string `json:"$ref"`
							Description string `json:"description"`
						} `json:"owner"`
						Summary struct {
							Type string `json:"type"`
							Const string `json:"const"`
							Description string `json:"description"`
							Deprecated string `json:"deprecated"`
						} `json:"summary"`
						VerifyKey struct {
							Type string `json:"type"`
							Description string `json:"description"`
						} `json:"verify_key"`
						Team struct {
							AnyOf []struct {
								Ref string `json:"$ref,omitempty"`
								Type string `json:"type,omitempty"`
							} `json:"anyOf"`
							Description string `json:"description"`
						} `json:"team"`
						GuildID struct {
							Ref string `json:"$ref"`
							Description string `json:"description"`
						} `json:"guild_id"`
						PrimarySkuID struct {
							Ref string `json:"$ref"`
							Description string `json:"description"`
						} `json:"primary_sku_id"`
						Slug struct {
							Type string `json:"type"`
							Description string `json:"description"`
						} `json:"slug"`
						CoverImage struct {
							Type string `json:"type"`
							Description string `json:"description"`
						} `json:"cover_image"`
						Flags struct {
							Ref string `json:"$ref"`
							Description string `json:"description"`
						} `json:"flags"`
					} `json:"properties"`
					AdditionalProperties bool `json:"additionalProperties"`
					Description string `json:"description"`
				} `json:"application"`
				ApplicationID struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"application_id"`
				MessageReference struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"message_reference"`
				Flags struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"flags"`
				ReferencedMessage struct {
					AnyOf []struct {
						Ref string `json:"$ref,omitempty"`
						Type string `json:"type,omitempty"`
					} `json:"anyOf"`
					Description string `json:"description"`
				} `json:"referenced_message"`
				Interaction struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"interaction"`
				Thread struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"thread"`
				Components struct {
					Type string `json:"type"`
					Items struct {
						Ref string `json:"$ref"`
					} `json:"items"`
					Description string `json:"description"`
				} `json:"components"`
				StickerItems struct {
					Type string `json:"type"`
					Items struct {
						Ref string `json:"$ref"`
					} `json:"items"`
					Description string `json:"description"`
				} `json:"sticker_items"`
				Stickers struct {
					Type string `json:"type"`
					Items struct {
						Ref string `json:"$ref"`
					} `json:"items"`
					Description string `json:"description"`
					Deprecated string `json:"deprecated"`
				} `json:"stickers"`
			} `json:"properties"`
			Required []string `json:"required"`
			AdditionalProperties bool `json:"additionalProperties"`
			Description string `json:"description"`
		} `json:"APIMessage"`
		APIGuildMember struct {
			Type string `json:"type"`
			Properties struct {
				User struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"user"`
				Nick struct {
					Type []string `json:"type"`
					Description string `json:"description"`
				} `json:"nick"`
				Avatar struct {
					Type []string `json:"type"`
					Description string `json:"description"`
				} `json:"avatar"`
				Roles struct {
					Type string `json:"type"`
					Items struct {
						Ref string `json:"$ref"`
					} `json:"items"`
					Description string `json:"description"`
				} `json:"roles"`
				JoinedAt struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"joined_at"`
				PremiumSince struct {
					Type []string `json:"type"`
					Description string `json:"description"`
				} `json:"premium_since"`
				Deaf struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"deaf"`
				Mute struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"mute"`
				Pending struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"pending"`
				CommunicationDisabledUntil struct {
					Type []string `json:"type"`
					Description string `json:"description"`
				} `json:"communication_disabled_until"`
			} `json:"properties"`
			Required []string `json:"required"`
			AdditionalProperties bool `json:"additionalProperties"`
			Description string `json:"description"`
		} `json:"APIGuildMember"`
		APIChannelMention struct {
			Type string `json:"type"`
			Properties struct {
				ID struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"id"`
				GuildID struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"guild_id"`
				Type struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"type"`
				Name struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"name"`
			} `json:"properties"`
			Required []string `json:"required"`
			AdditionalProperties bool `json:"additionalProperties"`
			Description string `json:"description"`
		} `json:"APIChannelMention"`
		APIAttachment struct {
			Type string `json:"type"`
			Properties struct {
				ID struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"id"`
				Filename struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"filename"`
				Description struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"description"`
				ContentType struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"content_type"`
				Size struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"size"`
				URL struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"url"`
				ProxyURL struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"proxy_url"`
				Height struct {
					Type []string `json:"type"`
					Description string `json:"description"`
				} `json:"height"`
				Width struct {
					Type []string `json:"type"`
					Description string `json:"description"`
				} `json:"width"`
				Ephemeral struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"ephemeral"`
			} `json:"properties"`
			Required []string `json:"required"`
			AdditionalProperties bool `json:"additionalProperties"`
			Description string `json:"description"`
		} `json:"APIAttachment"`
		APIEmbed struct {
			Type string `json:"type"`
			Properties struct {
				Title struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"title"`
				Type struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
					Deprecated string `json:"deprecated"`
				} `json:"type"`
				Description struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"description"`
				URL struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"url"`
				Timestamp struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"timestamp"`
				Color struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"color"`
				Footer struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"footer"`
				Image struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"image"`
				Thumbnail struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"thumbnail"`
				Video struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"video"`
				Provider struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"provider"`
				Author struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"author"`
				Fields struct {
					Type string `json:"type"`
					Items struct {
						Ref string `json:"$ref"`
					} `json:"items"`
					Description string `json:"description"`
				} `json:"fields"`
			} `json:"properties"`
			AdditionalProperties bool `json:"additionalProperties"`
			Description string `json:"description"`
		} `json:"APIEmbed"`
		EmbedType struct {
			Type string `json:"type"`
			Enum []string `json:"enum"`
			Description string `json:"description"`
			Deprecated string `json:"deprecated"`
		} `json:"EmbedType"`
		APIEmbedFooter struct {
			Type string `json:"type"`
			Properties struct {
				Text struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"text"`
				IconURL struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"icon_url"`
				ProxyIconURL struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"proxy_icon_url"`
			} `json:"properties"`
			Required []string `json:"required"`
			AdditionalProperties bool `json:"additionalProperties"`
			Description string `json:"description"`
		} `json:"APIEmbedFooter"`
		APIEmbedImage struct {
			Type string `json:"type"`
			Properties struct {
				URL struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"url"`
				ProxyURL struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"proxy_url"`
				Height struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"height"`
				Width struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"width"`
			} `json:"properties"`
			Required []string `json:"required"`
			AdditionalProperties bool `json:"additionalProperties"`
			Description string `json:"description"`
		} `json:"APIEmbedImage"`
		APIEmbedThumbnail struct {
			Type string `json:"type"`
			Properties struct {
				URL struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"url"`
				ProxyURL struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"proxy_url"`
				Height struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"height"`
				Width struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"width"`
			} `json:"properties"`
			Required []string `json:"required"`
			AdditionalProperties bool `json:"additionalProperties"`
			Description string `json:"description"`
		} `json:"APIEmbedThumbnail"`
		APIEmbedVideo struct {
			Type string `json:"type"`
			Properties struct {
				URL struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"url"`
				Height struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"height"`
				Width struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"width"`
			} `json:"properties"`
			AdditionalProperties bool `json:"additionalProperties"`
			Description string `json:"description"`
		} `json:"APIEmbedVideo"`
		APIEmbedProvider struct {
			Type string `json:"type"`
			Properties struct {
				Name struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"name"`
				URL struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"url"`
			} `json:"properties"`
			AdditionalProperties bool `json:"additionalProperties"`
			Description string `json:"description"`
		} `json:"APIEmbedProvider"`
		APIEmbedAuthor struct {
			Type string `json:"type"`
			Properties struct {
				Name struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"name"`
				URL struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"url"`
				IconURL struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"icon_url"`
				ProxyIconURL struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"proxy_icon_url"`
			} `json:"properties"`
			Required []string `json:"required"`
			AdditionalProperties bool `json:"additionalProperties"`
			Description string `json:"description"`
		} `json:"APIEmbedAuthor"`
		APIEmbedField struct {
			Type string `json:"type"`
			Properties struct {
				Name struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"name"`
				Value struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"value"`
				Inline struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"inline"`
			} `json:"properties"`
			Required []string `json:"required"`
			AdditionalProperties bool `json:"additionalProperties"`
			Description string `json:"description"`
		} `json:"APIEmbedField"`
		APIReaction struct {
			Type string `json:"type"`
			Properties struct {
				Count struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"count"`
				Me struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"me"`
				Emoji struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"emoji"`
			} `json:"properties"`
			Required []string `json:"required"`
			AdditionalProperties bool `json:"additionalProperties"`
			Description string `json:"description"`
		} `json:"APIReaction"`
		APIPartialEmoji struct {
			Type string `json:"type"`
			Properties struct {
				ID struct {
					AnyOf []struct {
						Ref string `json:"$ref,omitempty"`
						Type string `json:"type,omitempty"`
					} `json:"anyOf"`
					Description string `json:"description"`
				} `json:"id"`
				Name struct {
					Type []string `json:"type"`
					Description string `json:"description"`
				} `json:"name"`
				Animated struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"animated"`
			} `json:"properties"`
			Required []string `json:"required"`
			AdditionalProperties bool `json:"additionalProperties"`
			Description string `json:"description"`
		} `json:"APIPartialEmoji"`
		MessageType struct {
			Type string `json:"type"`
			Enum []int `json:"enum"`
			Description string `json:"description"`
		} `json:"MessageType"`
		APIMessageActivity struct {
			Type string `json:"type"`
			Properties struct {
				Type struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"type"`
				PartyID struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"party_id"`
			} `json:"properties"`
			Required []string `json:"required"`
			AdditionalProperties bool `json:"additionalProperties"`
			Description string `json:"description"`
		} `json:"APIMessageActivity"`
		MessageActivityType struct {
			Type string `json:"type"`
			Enum []int `json:"enum"`
			Description string `json:"description"`
		} `json:"MessageActivityType"`
		APITeam struct {
			Type string `json:"type"`
			Properties struct {
				Icon struct {
					Type []string `json:"type"`
					Description string `json:"description"`
				} `json:"icon"`
				ID struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"id"`
				Members struct {
					Type string `json:"type"`
					Items struct {
						Ref string `json:"$ref"`
					} `json:"items"`
					Description string `json:"description"`
				} `json:"members"`
				Name struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"name"`
				OwnerUserID struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"owner_user_id"`
			} `json:"properties"`
			Required []string `json:"required"`
			AdditionalProperties bool `json:"additionalProperties"`
			Description string `json:"description"`
		} `json:"APITeam"`
		APITeamMember struct {
			Type string `json:"type"`
			Properties struct {
				MembershipState struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"membership_state"`
				Permissions struct {
					Type string `json:"type"`
					Items struct {
						Type string `json:"type"`
						Const string `json:"const"`
					} `json:"items"`
					MinItems int `json:"minItems"`
					MaxItems int `json:"maxItems"`
					Description string `json:"description"`
				} `json:"permissions"`
				TeamID struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"team_id"`
				User struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"user"`
			} `json:"properties"`
			Required []string `json:"required"`
			AdditionalProperties bool `json:"additionalProperties"`
			Description string `json:"description"`
		} `json:"APITeamMember"`
		TeamMemberMembershipState struct {
			Type string `json:"type"`
			Enum []int `json:"enum"`
			Description string `json:"description"`
		} `json:"TeamMemberMembershipState"`
		ApplicationFlags struct {
			Type string `json:"type"`
			Enum []int `json:"enum"`
			Description string `json:"description"`
		} `json:"ApplicationFlags"`
		APIMessageReference struct {
			Type string `json:"type"`
			Properties struct {
				MessageID struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"message_id"`
				ChannelID struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"channel_id"`
				GuildID struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"guild_id"`
			} `json:"properties"`
			Required []string `json:"required"`
			AdditionalProperties bool `json:"additionalProperties"`
			Description string `json:"description"`
		} `json:"APIMessageReference"`
		MessageFlags struct {
			Type string `json:"type"`
			Enum []int `json:"enum"`
			Description string `json:"description"`
		} `json:"MessageFlags"`
		APIMessageInteraction struct {
			Type string `json:"type"`
			Properties struct {
				ID struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"id"`
				Type struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"type"`
				Name struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"name"`
				User struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"user"`
				Member struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"member"`
			} `json:"properties"`
			Required []string `json:"required"`
			AdditionalProperties bool `json:"additionalProperties"`
			Description string `json:"description"`
		} `json:"APIMessageInteraction"`
		InteractionType struct {
			Type string `json:"type"`
			Enum []int `json:"enum"`
			Description string `json:"description"`
		} `json:"InteractionType"`
		PartialAPIMessageInteractionGuildMember struct {
			Type string `json:"type"`
			Properties struct {
				Roles struct {
					Type string `json:"type"`
					Items struct {
						Ref string `json:"$ref"`
					} `json:"items"`
					Description string `json:"description"`
				} `json:"roles"`
				PremiumSince struct {
					Type []string `json:"type"`
					Description string `json:"description"`
				} `json:"premium_since"`
				Pending struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"pending"`
				Nick struct {
					Type []string `json:"type"`
					Description string `json:"description"`
				} `json:"nick"`
				Mute struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"mute"`
				JoinedAt struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"joined_at"`
				Deaf struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"deaf"`
				CommunicationDisabledUntil struct {
					Type []string `json:"type"`
					Description string `json:"description"`
				} `json:"communication_disabled_until"`
				Avatar struct {
					Type []string `json:"type"`
					Description string `json:"description"`
				} `json:"avatar"`
			} `json:"properties"`
			Required []string `json:"required"`
			AdditionalProperties bool `json:"additionalProperties"`
		} `json:"PartialAPIMessageInteractionGuildMember"`
		APIActionRowComponentAPIMessageActionRowComponent struct {
			Type string `json:"type"`
			Properties struct {
				Type struct {
					Type string `json:"type"`
					Const int `json:"const"`
					Description string `json:"description"`
				} `json:"type"`
				Components struct {
					Type string `json:"type"`
					Items struct {
						Ref string `json:"$ref"`
					} `json:"items"`
					Description string `json:"description"`
				} `json:"components"`
			} `json:"properties"`
			Required []string `json:"required"`
			AdditionalProperties bool `json:"additionalProperties"`
			Description string `json:"description"`
		} `json:"APIActionRowComponent<APIMessageActionRowComponent>"`
		APIBaseComponentEnum13545260102870528755135452601028581288941354526010033636105957764 struct {
			Type string `json:"type"`
			Properties struct {
				Type struct {
					Type string `json:"type"`
					Const int `json:"const"`
					Description string `json:"description"`
				} `json:"type"`
			} `json:"properties"`
			Required []string `json:"required"`
			AdditionalProperties bool `json:"additionalProperties"`
			Description string `json:"description"`
		} `json:"APIBaseComponent<enum-1354526010-28705-28755-1354526010-28581-28894-1354526010-0-33636105957764>"`
		APIMessageActionRowComponent struct {
			AnyOf []struct {
				Ref string `json:"$ref"`
			} `json:"anyOf"`
			Description string `json:"description"`
		} `json:"APIMessageActionRowComponent"`
		APIButtonComponent struct {
			AnyOf []struct {
				Ref string `json:"$ref"`
			} `json:"anyOf"`
		} `json:"APIButtonComponent"`
		APIButtonComponentWithCustomID struct {
			Type string `json:"type"`
			Properties struct {
				Type struct {
					Type string `json:"type"`
					Const int `json:"const"`
					Description string `json:"description"`
				} `json:"type"`
				Label struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"label"`
				Style struct {
					AnyOf []struct {
						Type string `json:"type"`
						Const int `json:"const"`
					} `json:"anyOf"`
					Description string `json:"description"`
				} `json:"style"`
				Emoji struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"emoji"`
				Disabled struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"disabled"`
				CustomID struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"custom_id"`
			} `json:"properties"`
			Required []string `json:"required"`
			AdditionalProperties bool `json:"additionalProperties"`
		} `json:"APIButtonComponentWithCustomId"`
		APIButtonComponentBaseEnum13545260103053930552135452601030405305931354526010033636Enum13545260103055330564135452601030405305931354526010033636Enum13545260103056530574135452601030405305931354526010033636Enum13545260103057530583135452601030405305931354526010033636 struct {
			Type string `json:"type"`
			Properties struct {
				Type struct {
					Type string `json:"type"`
					Const int `json:"const"`
					Description string `json:"description"`
				} `json:"type"`
				Label struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"label"`
				Style struct {
					AnyOf []struct {
						Type string `json:"type"`
						Const int `json:"const"`
					} `json:"anyOf"`
					Description string `json:"description"`
				} `json:"style"`
				Emoji struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"emoji"`
				Disabled struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"disabled"`
			} `json:"properties"`
			Required []string `json:"required"`
			AdditionalProperties bool `json:"additionalProperties"`
			Description string `json:"description"`
		} `json:"APIButtonComponentBase<(enum-1354526010-30539-30552-1354526010-30405-30593-1354526010-0-33636|enum-1354526010-30553-30564-1354526010-30405-30593-1354526010-0-33636|enum-1354526010-30565-30574-1354526010-30405-30593-1354526010-0-33636|enum-1354526010-30575-30583-1354526010-30405-30593-1354526010-0-33636)>"`
		APIBaseComponentEnum135452601028756287951354526010285812889413545260100336361131375322 struct {
			Type string `json:"type"`
			Properties struct {
				Type struct {
					Type string `json:"type"`
					Const int `json:"const"`
					Description string `json:"description"`
				} `json:"type"`
			} `json:"properties"`
			Required []string `json:"required"`
			AdditionalProperties bool `json:"additionalProperties"`
			Description string `json:"description"`
		} `json:"APIBaseComponent<enum-1354526010-28756-28795-1354526010-28581-28894-1354526010-0-336361131375322>"`
		APIMessageComponentEmoji struct {
			Type string `json:"type"`
			Properties struct {
				ID struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"id"`
				Name struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"name"`
				Animated struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"animated"`
			} `json:"properties"`
			AdditionalProperties bool `json:"additionalProperties"`
		} `json:"APIMessageComponentEmoji"`
		APIButtonComponentWithURL struct {
			Type string `json:"type"`
			Properties struct {
				Type struct {
					Type string `json:"type"`
					Const int `json:"const"`
					Description string `json:"description"`
				} `json:"type"`
				Label struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"label"`
				Style struct {
					Type string `json:"type"`
					Const int `json:"const"`
					Description string `json:"description"`
				} `json:"style"`
				Emoji struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"emoji"`
				Disabled struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"disabled"`
				URL struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"url"`
			} `json:"properties"`
			Required []string `json:"required"`
			AdditionalProperties bool `json:"additionalProperties"`
		} `json:"APIButtonComponentWithURL"`
		APIButtonComponentBaseEnum13545260103058430590135452601030405305931354526010033636 struct {
			Type string `json:"type"`
			Properties struct {
				Type struct {
					Type string `json:"type"`
					Const int `json:"const"`
					Description string `json:"description"`
				} `json:"type"`
				Label struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"label"`
				Style struct {
					Type string `json:"type"`
					Const int `json:"const"`
					Description string `json:"description"`
				} `json:"style"`
				Emoji struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"emoji"`
				Disabled struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"disabled"`
			} `json:"properties"`
			Required []string `json:"required"`
			AdditionalProperties bool `json:"additionalProperties"`
			Description string `json:"description"`
		} `json:"APIButtonComponentBase<enum-1354526010-30584-30590-1354526010-30405-30593-1354526010-0-33636>"`
		APISelectMenuComponent struct {
			Type string `json:"type"`
			Properties struct {
				Type struct {
					Type string `json:"type"`
					Const int `json:"const"`
					Description string `json:"description"`
				} `json:"type"`
				CustomID struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"custom_id"`
				Options struct {
					Type string `json:"type"`
					Items struct {
						Ref string `json:"$ref"`
					} `json:"items"`
					Description string `json:"description"`
				} `json:"options"`
				Placeholder struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"placeholder"`
				MinValues struct {
					Type string `json:"type"`
					Description string `json:"description"`
					Default int `json:"default"`
				} `json:"min_values"`
				MaxValues struct {
					Type string `json:"type"`
					Description string `json:"description"`
					Default int `json:"default"`
				} `json:"max_values"`
				Disabled struct {
					Type string `json:"type"`
					Description string `json:"description"`
					Default bool `json:"default"`
				} `json:"disabled"`
			} `json:"properties"`
			Required []string `json:"required"`
			AdditionalProperties bool `json:"additionalProperties"`
			Description string `json:"description"`
		} `json:"APISelectMenuComponent"`
		APIBaseComponentEnum13545260102879628844135452601028581288941354526010033636663308133 struct {
			Type string `json:"type"`
			Properties struct {
				Type struct {
					Type string `json:"type"`
					Const int `json:"const"`
					Description string `json:"description"`
				} `json:"type"`
			} `json:"properties"`
			Required []string `json:"required"`
			AdditionalProperties bool `json:"additionalProperties"`
			Description string `json:"description"`
		} `json:"APIBaseComponent<enum-1354526010-28796-28844-1354526010-28581-28894-1354526010-0-33636663308133>"`
		APISelectMenuOption struct {
			Type string `json:"type"`
			Properties struct {
				Label struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"label"`
				Value struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"value"`
				Description struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"description"`
				Emoji struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"emoji"`
				Default struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"default"`
			} `json:"properties"`
			Required []string `json:"required"`
			AdditionalProperties bool `json:"additionalProperties"`
			Description string `json:"description"`
		} `json:"APISelectMenuOption"`
		APIStickerItem struct {
			Type string `json:"type"`
			Properties struct {
				ID struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"id"`
				Name struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"name"`
				FormatType struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"format_type"`
			} `json:"properties"`
			Required []string `json:"required"`
			AdditionalProperties bool `json:"additionalProperties"`
			Description string `json:"description"`
		} `json:"APIStickerItem"`
		StickerFormatType struct {
			Type string `json:"type"`
			Enum []int `json:"enum"`
			Description string `json:"description"`
		} `json:"StickerFormatType"`
		APISticker struct {
			Type string `json:"type"`
			Properties struct {
				ID struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"id"`
				PackID struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"pack_id"`
				Name struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"name"`
				Description struct {
					Type []string `json:"type"`
					Description string `json:"description"`
				} `json:"description"`
				Tags struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"tags"`
				Asset struct {
					Type string `json:"type"`
					Const string `json:"const"`
					Description string `json:"description"`
					Deprecated string `json:"deprecated"`
				} `json:"asset"`
				Type struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"type"`
				FormatType struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"format_type"`
				Available struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"available"`
				GuildID struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"guild_id"`
				User struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"user"`
				SortValue struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"sort_value"`
			} `json:"properties"`
			Required []string `json:"required"`
			AdditionalProperties bool `json:"additionalProperties"`
			Description string `json:"description"`
		} `json:"APISticker"`
		StickerType struct {
			Type string `json:"type"`
			Enum []int `json:"enum"`
			Description string `json:"description"`
		} `json:"StickerType"`
		APIFollowedChannel struct {
			Type string `json:"type"`
			Properties struct {
				ChannelID struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"channel_id"`
				WebhookID struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"webhook_id"`
			} `json:"properties"`
			Required []string `json:"required"`
			AdditionalProperties bool `json:"additionalProperties"`
			Description string `json:"description"`
		} `json:"APIFollowedChannel"`
		APIThreadList struct {
			Type string `json:"type"`
			Properties struct {
				Threads struct {
					Type string `json:"type"`
					Items struct {
						Ref string `json:"$ref"`
					} `json:"items"`
					Description string `json:"description"`
				} `json:"threads"`
				Members struct {
					Type string `json:"type"`
					Items struct {
						Ref string `json:"$ref"`
					} `json:"items"`
					Description string `json:"description"`
				} `json:"members"`
				HasMore struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"has_more"`
			} `json:"properties"`
			Required []string `json:"required"`
			AdditionalProperties bool `json:"additionalProperties"`
		} `json:"APIThreadList"`
		AllowedMentionsTypes struct {
			Type string `json:"type"`
			Enum []string `json:"enum"`
			Description string `json:"description"`
		} `json:"AllowedMentionsTypes"`
		APIAllowedMentions struct {
			Type string `json:"type"`
			Properties struct {
				Parse struct {
					Type string `json:"type"`
					Items struct {
						Ref string `json:"$ref"`
					} `json:"items"`
					Description string `json:"description"`
				} `json:"parse"`
				Roles struct {
					Type string `json:"type"`
					Items struct {
						Ref string `json:"$ref"`
					} `json:"items"`
					Description string `json:"description"`
				} `json:"roles"`
				Users struct {
					Type string `json:"type"`
					Items struct {
						Ref string `json:"$ref"`
					} `json:"items"`
					Description string `json:"description"`
				} `json:"users"`
				RepliedUser struct {
					Type string `json:"type"`
					Description string `json:"description"`
					Default bool `json:"default"`
				} `json:"replied_user"`
			} `json:"properties"`
			AdditionalProperties bool `json:"additionalProperties"`
			Description string `json:"description"`
		} `json:"APIAllowedMentions"`
		ComponentType struct {
			Type string `json:"type"`
			Enum []int `json:"enum"`
			Description string `json:"description"`
		} `json:"ComponentType"`
		ButtonStyle struct {
			Type string `json:"type"`
			Enum []int `json:"enum"`
			Description string `json:"description"`
		} `json:"ButtonStyle"`
		TextInputStyle struct {
			Type string `json:"type"`
			Enum []int `json:"enum"`
			Description string `json:"description"`
		} `json:"TextInputStyle"`
		APITextInputComponent struct {
			Type string `json:"type"`
			Properties struct {
				Type struct {
					Type string `json:"type"`
					Const int `json:"const"`
					Description string `json:"description"`
				} `json:"type"`
				Style struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"style"`
				CustomID struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"custom_id"`
				Label struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"label"`
				Placeholder struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"placeholder"`
				Value struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"value"`
				MinLength struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"min_length"`
				MaxLength struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"max_length"`
				Required struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"required"`
			} `json:"properties"`
			Required []string `json:"required"`
			AdditionalProperties bool `json:"additionalProperties"`
			Description string `json:"description"`
		} `json:"APITextInputComponent"`
		APIBaseComponentEnum135452601028845288911354526010285812889413545260100336361182532533 struct {
			Type string `json:"type"`
			Properties struct {
				Type struct {
					Type string `json:"type"`
					Const int `json:"const"`
					Description string `json:"description"`
				} `json:"type"`
			} `json:"properties"`
			Required []string `json:"required"`
			AdditionalProperties bool `json:"additionalProperties"`
			Description string `json:"description"`
		} `json:"APIBaseComponent<enum-1354526010-28845-28891-1354526010-28581-28894-1354526010-0-336361182532533>"`
		APIMessageComponent struct {
			AnyOf []struct {
				Ref string `json:"$ref"`
			} `json:"anyOf"`
			Description string `json:"description"`
		} `json:"APIMessageComponent"`
		APIModalComponent struct {
			AnyOf []struct {
				Ref string `json:"$ref"`
			} `json:"anyOf"`
		} `json:"APIModalComponent"`
		APIModalActionRowComponent struct {
			Ref string `json:"$ref"`
		} `json:"APIModalActionRowComponent"`
		APIActionRowComponentAPIModalActionRowComponent struct {
			Type string `json:"type"`
			Properties struct {
				Type struct {
					Type string `json:"type"`
					Const int `json:"const"`
					Description string `json:"description"`
				} `json:"type"`
				Components struct {
					Type string `json:"type"`
					Items struct {
						Ref string `json:"$ref"`
					} `json:"items"`
					Description string `json:"description"`
				} `json:"components"`
			} `json:"properties"`
			Required []string `json:"required"`
			AdditionalProperties bool `json:"additionalProperties"`
			Description string `json:"description"`
		} `json:"APIActionRowComponent<APIModalActionRowComponent>"`
		APIActionRowComponentTypes struct {
			AnyOf []struct {
				Ref string `json:"$ref"`
			} `json:"anyOf"`
		} `json:"APIActionRowComponentTypes"`
	} `json:"definitions"`
}