type AutoGenerated struct {
	Definitions struct {
		APIStageInstanceGuildScheduledEvent struct {
			Type string `json:"type"`
			Properties struct {
				ID struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"id"`
				GuildID struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"guild_id"`
				ChannelID struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"channel_id"`
				CreatorID struct {
					AnyOf []struct {
						Ref string `json:"$ref,omitempty"`
						Type string `json:"type,omitempty"`
					} `json:"anyOf"`
					Description string `json:"description"`
				} `json:"creator_id"`
				Name struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"name"`
				Description struct {
					Type []string `json:"type"`
					Description string `json:"description"`
				} `json:"description"`
				ScheduledStartTime struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"scheduled_start_time"`
				ScheduledEndTime struct {
					Type []string `json:"type"`
					Description string `json:"description"`
				} `json:"scheduled_end_time"`
				PrivacyLevel struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"privacy_level"`
				Status struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"status"`
				EntityType struct {
					Type string `json:"type"`
					Const int `json:"const"`
					Description string `json:"description"`
				} `json:"entity_type"`
				EntityID struct {
					AnyOf []struct {
						Ref string `json:"$ref,omitempty"`
						Type string `json:"type,omitempty"`
					} `json:"anyOf"`
					Description string `json:"description"`
				} `json:"entity_id"`
				EntityMetadata struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"entity_metadata"`
				Creator struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"creator"`
				UserCount struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"user_count"`
				Image struct {
					Type []string `json:"type"`
					Description string `json:"description"`
				} `json:"image"`
			} `json:"properties"`
			Required []string `json:"required"`
			AdditionalProperties bool `json:"additionalProperties"`
		} `json:"APIStageInstanceGuildScheduledEvent"`
		Snowflake struct {
			Type string `json:"type"`
			Description string `json:"description"`
		} `json:"Snowflake"`
		GuildScheduledEventPrivacyLevel struct {
			Type string `json:"type"`
			Const int `json:"const"`
			Description string `json:"description"`
		} `json:"GuildScheduledEventPrivacyLevel"`
		GuildScheduledEventStatus struct {
			Type string `json:"type"`
			Enum []int `json:"enum"`
			Description string `json:"description"`
		} `json:"GuildScheduledEventStatus"`
		APIGuildScheduledEventEntityMetadata struct {
			Type string `json:"type"`
			Properties struct {
				Location struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"location"`
			} `json:"properties"`
			AdditionalProperties bool `json:"additionalProperties"`
			Description string `json:"description"`
		} `json:"APIGuildScheduledEventEntityMetadata"`
		APIUser struct {
			Type string `json:"type"`
			Properties struct {
				ID struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"id"`
				Username struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"username"`
				Discriminator struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"discriminator"`
				Avatar struct {
					Type []string `json:"type"`
					Description string `json:"description"`
				} `json:"avatar"`
				Bot struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"bot"`
				System struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"system"`
				MfaEnabled struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"mfa_enabled"`
				Banner struct {
					Type []string `json:"type"`
					Description string `json:"description"`
				} `json:"banner"`
				AccentColor struct {
					Type []string `json:"type"`
					Description string `json:"description"`
				} `json:"accent_color"`
				Locale struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"locale"`
				Verified struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"verified"`
				Email struct {
					Type []string `json:"type"`
					Description string `json:"description"`
				} `json:"email"`
				Flags struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"flags"`
				PremiumType struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"premium_type"`
				PublicFlags struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"public_flags"`
			} `json:"properties"`
			Required []string `json:"required"`
			AdditionalProperties bool `json:"additionalProperties"`
			Description string `json:"description"`
		} `json:"APIUser"`
		UserFlags struct {
			Type string `json:"type"`
			Enum []int `json:"enum"`
			Description string `json:"description"`
		} `json:"UserFlags"`
		UserPremiumType struct {
			Type string `json:"type"`
			Enum []int `json:"enum"`
			Description string `json:"description"`
		} `json:"UserPremiumType"`
		APIVoiceGuildScheduledEvent struct {
			Type string `json:"type"`
			Properties struct {
				ID struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"id"`
				GuildID struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"guild_id"`
				ChannelID struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"channel_id"`
				CreatorID struct {
					AnyOf []struct {
						Ref string `json:"$ref,omitempty"`
						Type string `json:"type,omitempty"`
					} `json:"anyOf"`
					Description string `json:"description"`
				} `json:"creator_id"`
				Name struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"name"`
				Description struct {
					Type []string `json:"type"`
					Description string `json:"description"`
				} `json:"description"`
				ScheduledStartTime struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"scheduled_start_time"`
				ScheduledEndTime struct {
					Type []string `json:"type"`
					Description string `json:"description"`
				} `json:"scheduled_end_time"`
				PrivacyLevel struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"privacy_level"`
				Status struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"status"`
				EntityType struct {
					Type string `json:"type"`
					Const int `json:"const"`
					Description string `json:"description"`
				} `json:"entity_type"`
				EntityID struct {
					AnyOf []struct {
						Ref string `json:"$ref,omitempty"`
						Type string `json:"type,omitempty"`
					} `json:"anyOf"`
					Description string `json:"description"`
				} `json:"entity_id"`
				EntityMetadata struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"entity_metadata"`
				Creator struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"creator"`
				UserCount struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"user_count"`
				Image struct {
					Type []string `json:"type"`
					Description string `json:"description"`
				} `json:"image"`
			} `json:"properties"`
			Required []string `json:"required"`
			AdditionalProperties bool `json:"additionalProperties"`
		} `json:"APIVoiceGuildScheduledEvent"`
		APIExternalGuildScheduledEvent struct {
			Type string `json:"type"`
			Properties struct {
				ID struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"id"`
				GuildID struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"guild_id"`
				ChannelID struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"channel_id"`
				CreatorID struct {
					AnyOf []struct {
						Ref string `json:"$ref,omitempty"`
						Type string `json:"type,omitempty"`
					} `json:"anyOf"`
					Description string `json:"description"`
				} `json:"creator_id"`
				Name struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"name"`
				Description struct {
					Type []string `json:"type"`
					Description string `json:"description"`
				} `json:"description"`
				ScheduledStartTime struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"scheduled_start_time"`
				ScheduledEndTime struct {
					Type []string `json:"type"`
					Description string `json:"description"`
				} `json:"scheduled_end_time"`
				PrivacyLevel struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"privacy_level"`
				Status struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"status"`
				EntityType struct {
					Type string `json:"type"`
					Const int `json:"const"`
					Description string `json:"description"`
				} `json:"entity_type"`
				EntityID struct {
					AnyOf []struct {
						Ref string `json:"$ref,omitempty"`
						Type string `json:"type,omitempty"`
					} `json:"anyOf"`
					Description string `json:"description"`
				} `json:"entity_id"`
				EntityMetadata struct {
					Type string `json:"type"`
					Properties struct {
						Location struct {
							Type string `json:"type"`
							Description string `json:"description"`
						} `json:"location"`
					} `json:"properties"`
					AdditionalProperties bool `json:"additionalProperties"`
					Description string `json:"description"`
				} `json:"entity_metadata"`
				Creator struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"creator"`
				UserCount struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"user_count"`
				Image struct {
					Type []string `json:"type"`
					Description string `json:"description"`
				} `json:"image"`
			} `json:"properties"`
			Required []string `json:"required"`
			AdditionalProperties bool `json:"additionalProperties"`
		} `json:"APIExternalGuildScheduledEvent"`
		APIGuildScheduledEvent struct {
			AnyOf []struct {
				Ref string `json:"$ref"`
			} `json:"anyOf"`
			Description string `json:"description"`
		} `json:"APIGuildScheduledEvent"`
		GuildScheduledEventEntityType struct {
			Type string `json:"type"`
			Enum []int `json:"enum"`
			Description string `json:"description"`
		} `json:"GuildScheduledEventEntityType"`
		APIGuildScheduledEventUser struct {
			Type string `json:"type"`
			Properties struct {
				GuildScheduledEventID struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"guild_scheduled_event_id"`
				User struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"user"`
				Member struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"member"`
			} `json:"properties"`
			Required []string `json:"required"`
			AdditionalProperties bool `json:"additionalProperties"`
			Description string `json:"description"`
		} `json:"APIGuildScheduledEventUser"`
		APIGuildMember struct {
			Type string `json:"type"`
			Properties struct {
				User struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"user"`
				Nick struct {
					Type []string `json:"type"`
					Description string `json:"description"`
				} `json:"nick"`
				Avatar struct {
					Type []string `json:"type"`
					Description string `json:"description"`
				} `json:"avatar"`
				Roles struct {
					Type string `json:"type"`
					Items struct {
						Ref string `json:"$ref"`
					} `json:"items"`
					Description string `json:"description"`
				} `json:"roles"`
				JoinedAt struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"joined_at"`
				PremiumSince struct {
					Type []string `json:"type"`
					Description string `json:"description"`
				} `json:"premium_since"`
				Deaf struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"deaf"`
				Mute struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"mute"`
				Pending struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"pending"`
				CommunicationDisabledUntil struct {
					Type []string `json:"type"`
					Description string `json:"description"`
				} `json:"communication_disabled_until"`
			} `json:"properties"`
			Required []string `json:"required"`
			AdditionalProperties bool `json:"additionalProperties"`
			Description string `json:"description"`
		} `json:"APIGuildMember"`
	} `json:"definitions"`
}