type AutoGenerated struct {
	Definitions struct {
		RESTGetAPIGatewayResult struct {
			Ref string `json:"$ref"`
			Description string `json:"description"`
			Deprecated string `json:"deprecated"`
		} `json:"RESTGetAPIGatewayResult"`
		APIGatewayInfo struct {
			Type string `json:"type"`
			Properties struct {
				URL struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"url"`
			} `json:"properties"`
			Required []string `json:"required"`
			AdditionalProperties bool `json:"additionalProperties"`
			Description string `json:"description"`
			Deprecated string `json:"deprecated"`
		} `json:"APIGatewayInfo"`
		RESTGetAPIGatewayBotResult struct {
			Ref string `json:"$ref"`
			Description string `json:"description"`
			Deprecated string `json:"deprecated"`
		} `json:"RESTGetAPIGatewayBotResult"`
		APIGatewayBotInfo struct {
			Type string `json:"type"`
			Properties struct {
				URL struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"url"`
				Shards struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"shards"`
				SessionStartLimit struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"session_start_limit"`
			} `json:"properties"`
			Required []string `json:"required"`
			AdditionalProperties bool `json:"additionalProperties"`
			Description string `json:"description"`
			Deprecated string `json:"deprecated"`
		} `json:"APIGatewayBotInfo"`
		APIGatewaySessionStartLimit struct {
			Type string `json:"type"`
			Properties struct {
				Total struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"total"`
				Remaining struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"remaining"`
				ResetAfter struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"reset_after"`
				MaxConcurrency struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"max_concurrency"`
			} `json:"properties"`
			Required []string `json:"required"`
			AdditionalProperties bool `json:"additionalProperties"`
			Description string `json:"description"`
			Deprecated string `json:"deprecated"`
		} `json:"APIGatewaySessionStartLimit"`
	} `json:"definitions"`
}