type AutoGenerated struct {
	Definitions struct {
		RESTGetAPICurrentUserResult struct {
			Ref string `json:"$ref"`
			Description string `json:"description"`
			Deprecated string `json:"deprecated"`
		} `json:"RESTGetAPICurrentUserResult"`
		APIUser struct {
			Type string `json:"type"`
			Properties struct {
				ID struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"id"`
				Username struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"username"`
				Discriminator struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"discriminator"`
				Avatar struct {
					Type []string `json:"type"`
					Description string `json:"description"`
				} `json:"avatar"`
				Bot struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"bot"`
				System struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"system"`
				MfaEnabled struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"mfa_enabled"`
				Banner struct {
					Type []string `json:"type"`
					Description string `json:"description"`
				} `json:"banner"`
				AccentColor struct {
					Type []string `json:"type"`
					Description string `json:"description"`
				} `json:"accent_color"`
				Locale struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"locale"`
				Verified struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"verified"`
				Email struct {
					Type []string `json:"type"`
					Description string `json:"description"`
				} `json:"email"`
				Flags struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"flags"`
				PremiumType struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"premium_type"`
				PublicFlags struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"public_flags"`
			} `json:"properties"`
			Required []string `json:"required"`
			AdditionalProperties bool `json:"additionalProperties"`
			Description string `json:"description"`
			Deprecated string `json:"deprecated"`
		} `json:"APIUser"`
		Snowflake struct {
			Type string `json:"type"`
			Description string `json:"description"`
		} `json:"Snowflake"`
		UserFlags struct {
			Type string `json:"type"`
			Enum []int `json:"enum"`
			Description string `json:"description"`
			Deprecated string `json:"deprecated"`
		} `json:"UserFlags"`
		UserPremiumType struct {
			Type string `json:"type"`
			Enum []int `json:"enum"`
			Description string `json:"description"`
			Deprecated string `json:"deprecated"`
		} `json:"UserPremiumType"`
		RESTGetAPIUserResult struct {
			Ref string `json:"$ref"`
			Description string `json:"description"`
			Deprecated string `json:"deprecated"`
		} `json:"RESTGetAPIUserResult"`
		RESTGetCurrentUserGuildMemberResult struct {
			Ref string `json:"$ref"`
			Description string `json:"description"`
			Deprecated string `json:"deprecated"`
		} `json:"RESTGetCurrentUserGuildMemberResult"`
		APIGuildMember struct {
			Type string `json:"type"`
			Properties struct {
				User struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"user"`
				Nick struct {
					Type []string `json:"type"`
					Description string `json:"description"`
				} `json:"nick"`
				Avatar struct {
					Type []string `json:"type"`
					Description string `json:"description"`
				} `json:"avatar"`
				Roles struct {
					Type string `json:"type"`
					Items struct {
						Ref string `json:"$ref"`
					} `json:"items"`
					Description string `json:"description"`
				} `json:"roles"`
				JoinedAt struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"joined_at"`
				PremiumSince struct {
					Type []string `json:"type"`
					Description string `json:"description"`
				} `json:"premium_since"`
				Deaf struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"deaf"`
				Mute struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"mute"`
				Pending struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"pending"`
				CommunicationDisabledUntil struct {
					Type []string `json:"type"`
					Description string `json:"description"`
				} `json:"communication_disabled_until"`
			} `json:"properties"`
			Required []string `json:"required"`
			AdditionalProperties bool `json:"additionalProperties"`
			Description string `json:"description"`
			Deprecated string `json:"deprecated"`
		} `json:"APIGuildMember"`
		RESTPatchAPICurrentUserJSONBody struct {
			Ref string `json:"$ref"`
			Description string `json:"description"`
			Deprecated string `json:"deprecated"`
		} `json:"RESTPatchAPICurrentUserJSONBody"`
		AddUndefinedToPossiblyUndefinedPropertiesOfInterfaceStructure94726783813381532947267838128415339472678381036153494726783803987 struct {
			Type string `json:"type"`
			Properties struct {
				Username struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"username"`
				Avatar struct {
					Type []string `json:"type"`
					Description string `json:"description"`
				} `json:"avatar"`
			} `json:"properties"`
			AdditionalProperties bool `json:"additionalProperties"`
			Description string `json:"description"`
		} `json:"AddUndefinedToPossiblyUndefinedPropertiesOfInterface<structure-947267838-1338-1532-947267838-1284-1533-947267838-1036-1534-947267838-0-3987>"`
		RESTPatchAPICurrentUserResult struct {
			Ref string `json:"$ref"`
			Description string `json:"description"`
			Deprecated string `json:"deprecated"`
		} `json:"RESTPatchAPICurrentUserResult"`
		RESTGetAPICurrentUserGuildsQuery struct {
			Type string `json:"type"`
			Properties struct {
				Before struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"before"`
				After struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"after"`
				Limit struct {
					Type string `json:"type"`
					Description string `json:"description"`
					Default int `json:"default"`
				} `json:"limit"`
			} `json:"properties"`
			AdditionalProperties bool `json:"additionalProperties"`
			Description string `json:"description"`
			Deprecated string `json:"deprecated"`
		} `json:"RESTGetAPICurrentUserGuildsQuery"`
		RESTAPIPartialCurrentUserGuild struct {
			Type string `json:"type"`
			Properties struct {
				ID struct {
					Ref string `json:"$ref"`
				} `json:"id"`
				Name struct {
					Type string `json:"type"`
				} `json:"name"`
				Icon struct {
					Type []string `json:"type"`
				} `json:"icon"`
				Owner struct {
					Type string `json:"type"`
				} `json:"owner"`
				Features struct {
					Type string `json:"type"`
					Items struct {
						Ref string `json:"$ref"`
					} `json:"items"`
				} `json:"features"`
				Permissions struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"permissions"`
			} `json:"properties"`
			Required []string `json:"required"`
			AdditionalProperties bool `json:"additionalProperties"`
			Deprecated string `json:"deprecated"`
		} `json:"RESTAPIPartialCurrentUserGuild"`
		GuildFeature struct {
			Type string `json:"type"`
			Enum []string `json:"enum"`
			Description string `json:"description"`
			Deprecated string `json:"deprecated"`
		} `json:"GuildFeature"`
		RESTGetAPICurrentUserGuildsResult struct {
			Type string `json:"type"`
			Items struct {
				Ref string `json:"$ref"`
			} `json:"items"`
			Description string `json:"description"`
			Deprecated string `json:"deprecated"`
		} `json:"RESTGetAPICurrentUserGuildsResult"`
		RESTPostAPICurrentUserCreateDMChannelJSONBody struct {
			Type string `json:"type"`
			Properties struct {
				RecipientID struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"recipient_id"`
			} `json:"properties"`
			Required []string `json:"required"`
			AdditionalProperties bool `json:"additionalProperties"`
			Description string `json:"description"`
			Deprecated string `json:"deprecated"`
		} `json:"RESTPostAPICurrentUserCreateDMChannelJSONBody"`
		RESTPostAPICurrentUserCreateDMChannelResult struct {
			Ref string `json:"$ref"`
			Description string `json:"description"`
			Deprecated string `json:"deprecated"`
		} `json:"RESTPostAPICurrentUserCreateDMChannelResult"`
		APIChannel struct {
			AnyOf []struct {
				Ref string `json:"$ref"`
			} `json:"anyOf"`
			Description string `json:"description"`
			Deprecated string `json:"deprecated"`
		} `json:"APIChannel"`
		APIGroupDMChannel struct {
			Type string `json:"type"`
			Properties struct {
				ID struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"id"`
				Type struct {
					Type string `json:"type"`
					Const int `json:"const"`
					Description string `json:"description"`
				} `json:"type"`
				Name struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"name"`
				LastMessageID struct {
					AnyOf []struct {
						Ref string `json:"$ref,omitempty"`
						Type string `json:"type,omitempty"`
					} `json:"anyOf"`
					Description string `json:"description"`
				} `json:"last_message_id"`
				Recipients struct {
					Type string `json:"type"`
					Items struct {
						Ref string `json:"$ref"`
					} `json:"items"`
					Description string `json:"description"`
				} `json:"recipients"`
				ApplicationID struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"application_id"`
				Icon struct {
					Type []string `json:"type"`
					Description string `json:"description"`
				} `json:"icon"`
				OwnerID struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"owner_id"`
			} `json:"properties"`
			AdditionalProperties bool `json:"additionalProperties"`
			Required []string `json:"required"`
			Deprecated string `json:"deprecated"`
		} `json:"APIGroupDMChannel"`
		APITextBasedChannelEnum12254432917712777512254432917308847112254432910358711767421466 struct {
			Type string `json:"type"`
			Properties struct {
				ID struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"id"`
				Type struct {
					Type string `json:"type"`
					Const int `json:"const"`
					Description string `json:"description"`
				} `json:"type"`
				Name struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"name"`
				LastMessageID struct {
					AnyOf []struct {
						Ref string `json:"$ref,omitempty"`
						Type string `json:"type,omitempty"`
					} `json:"anyOf"`
					Description string `json:"description"`
				} `json:"last_message_id"`
			} `json:"properties"`
			AdditionalProperties bool `json:"additionalProperties"`
			Required []string `json:"required"`
			Deprecated string `json:"deprecated"`
		} `json:"APITextBasedChannel<enum-1225443291-7712-7775-1225443291-7308-8471-1225443291-0-358711767421466>"`
		APIChannelBaseEnum12254432917712777512254432917308847112254432910358711767421466 struct {
			Type string `json:"type"`
			Properties struct {
				ID struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"id"`
				Type struct {
					Type string `json:"type"`
					Const int `json:"const"`
					Description string `json:"description"`
				} `json:"type"`
				Name struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"name"`
			} `json:"properties"`
			Required []string `json:"required"`
			AdditionalProperties bool `json:"additionalProperties"`
			Description string `json:"description"`
			Deprecated string `json:"deprecated"`
		} `json:"APIChannelBase<enum-1225443291-7712-7775-1225443291-7308-8471-1225443291-0-358711767421466>"`
		APIPartialChannel struct {
			Type string `json:"type"`
			Properties struct {
				ID struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"id"`
				Type struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"type"`
				Name struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"name"`
			} `json:"properties"`
			Required []string `json:"required"`
			AdditionalProperties bool `json:"additionalProperties"`
			Description string `json:"description"`
			Deprecated string `json:"deprecated"`
		} `json:"APIPartialChannel"`
		ChannelType struct {
			Type string `json:"type"`
			Enum []int `json:"enum"`
			Description string `json:"description"`
			Deprecated string `json:"deprecated"`
		} `json:"ChannelType"`
		APIDMChannel struct {
			Type string `json:"type"`
			Properties struct {
				ID struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"id"`
				Type struct {
					Type string `json:"type"`
					Const int `json:"const"`
					Description string `json:"description"`
				} `json:"type"`
				Name struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"name"`
				LastMessageID struct {
					AnyOf []struct {
						Ref string `json:"$ref,omitempty"`
						Type string `json:"type,omitempty"`
					} `json:"anyOf"`
					Description string `json:"description"`
				} `json:"last_message_id"`
				Recipients struct {
					Type string `json:"type"`
					Items struct {
						Ref string `json:"$ref"`
					} `json:"items"`
					Description string `json:"description"`
				} `json:"recipients"`
			} `json:"properties"`
			AdditionalProperties bool `json:"additionalProperties"`
			Required []string `json:"required"`
			Deprecated string `json:"deprecated"`
		} `json:"APIDMChannel"`
		APITextBasedChannelEnum1225443291760476531225443291730884711225443291035871102715350 struct {
			Type string `json:"type"`
			Properties struct {
				ID struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"id"`
				Type struct {
					Type string `json:"type"`
					Const int `json:"const"`
					Description string `json:"description"`
				} `json:"type"`
				Name struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"name"`
				LastMessageID struct {
					AnyOf []struct {
						Ref string `json:"$ref,omitempty"`
						Type string `json:"type,omitempty"`
					} `json:"anyOf"`
					Description string `json:"description"`
				} `json:"last_message_id"`
			} `json:"properties"`
			AdditionalProperties bool `json:"additionalProperties"`
			Required []string `json:"required"`
			Deprecated string `json:"deprecated"`
		} `json:"APITextBasedChannel<enum-1225443291-7604-7653-1225443291-7308-8471-1225443291-0-35871102715350>"`
		APIChannelBaseEnum1225443291760476531225443291730884711225443291035871102715350 struct {
			Type string `json:"type"`
			Properties struct {
				ID struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"id"`
				Type struct {
					Type string `json:"type"`
					Const int `json:"const"`
					Description string `json:"description"`
				} `json:"type"`
				Name struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"name"`
			} `json:"properties"`
			Required []string `json:"required"`
			AdditionalProperties bool `json:"additionalProperties"`
			Description string `json:"description"`
			Deprecated string `json:"deprecated"`
		} `json:"APIChannelBase<enum-1225443291-7604-7653-1225443291-7308-8471-1225443291-0-35871102715350>"`
		APITextChannel struct {
			Type string `json:"type"`
			Properties struct {
				ID struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"id"`
				Type struct {
					Type string `json:"type"`
					Const int `json:"const"`
					Description string `json:"description"`
				} `json:"type"`
				Name struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"name"`
				GuildID struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"guild_id"`
				PermissionOverwrites struct {
					Type string `json:"type"`
					Items struct {
						Ref string `json:"$ref"`
					} `json:"items"`
					Description string `json:"description"`
				} `json:"permission_overwrites"`
				Position struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"position"`
				ParentID struct {
					AnyOf []struct {
						Ref string `json:"$ref,omitempty"`
						Type string `json:"type,omitempty"`
					} `json:"anyOf"`
					Description string `json:"description"`
				} `json:"parent_id"`
				Nsfw struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"nsfw"`
				LastMessageID struct {
					AnyOf []struct {
						Ref string `json:"$ref,omitempty"`
						Type string `json:"type,omitempty"`
					} `json:"anyOf"`
					Description string `json:"description"`
				} `json:"last_message_id"`
				Topic struct {
					Type []string `json:"type"`
					Description string `json:"description"`
				} `json:"topic"`
				LastPinTimestamp struct {
					Type []string `json:"type"`
					Description string `json:"description"`
				} `json:"last_pin_timestamp"`
				RateLimitPerUser struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"rate_limit_per_user"`
			} `json:"properties"`
			AdditionalProperties bool `json:"additionalProperties"`
			Required []string `json:"required"`
			Deprecated string `json:"deprecated"`
		} `json:"APITextChannel"`
		APIGuildTextChannelEnum1225443291754876031225443291730884711225443291035871732917173 struct {
			Type string `json:"type"`
			Properties struct {
				ID struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"id"`
				Type struct {
					Type string `json:"type"`
					Const int `json:"const"`
					Description string `json:"description"`
				} `json:"type"`
				Name struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"name"`
				GuildID struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"guild_id"`
				PermissionOverwrites struct {
					Type string `json:"type"`
					Items struct {
						Ref string `json:"$ref"`
					} `json:"items"`
					Description string `json:"description"`
				} `json:"permission_overwrites"`
				Position struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"position"`
				ParentID struct {
					AnyOf []struct {
						Ref string `json:"$ref,omitempty"`
						Type string `json:"type,omitempty"`
					} `json:"anyOf"`
					Description string `json:"description"`
				} `json:"parent_id"`
				Nsfw struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"nsfw"`
				LastMessageID struct {
					AnyOf []struct {
						Ref string `json:"$ref,omitempty"`
						Type string `json:"type,omitempty"`
					} `json:"anyOf"`
					Description string `json:"description"`
				} `json:"last_message_id"`
				Topic struct {
					Type []string `json:"type"`
					Description string `json:"description"`
				} `json:"topic"`
				LastPinTimestamp struct {
					Type []string `json:"type"`
					Description string `json:"description"`
				} `json:"last_pin_timestamp"`
			} `json:"properties"`
			AdditionalProperties bool `json:"additionalProperties"`
			Required []string `json:"required"`
			Deprecated string `json:"deprecated"`
		} `json:"APIGuildTextChannel<enum-1225443291-7548-7603-1225443291-7308-8471-1225443291-0-35871732917173>"`
		APITextBasedChannelEnum1225443291754876031225443291730884711225443291035871732917173 struct {
			Type string `json:"type"`
			Properties struct {
				ID struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"id"`
				Type struct {
					Type string `json:"type"`
					Const int `json:"const"`
					Description string `json:"description"`
				} `json:"type"`
				Name struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"name"`
				LastMessageID struct {
					AnyOf []struct {
						Ref string `json:"$ref,omitempty"`
						Type string `json:"type,omitempty"`
					} `json:"anyOf"`
					Description string `json:"description"`
				} `json:"last_message_id"`
			} `json:"properties"`
			AdditionalProperties bool `json:"additionalProperties"`
			Required []string `json:"required"`
			Deprecated string `json:"deprecated"`
		} `json:"APITextBasedChannel<enum-1225443291-7548-7603-1225443291-7308-8471-1225443291-0-35871732917173>"`
		APIChannelBaseEnum1225443291754876031225443291730884711225443291035871732917173 struct {
			Type string `json:"type"`
			Properties struct {
				ID struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"id"`
				Type struct {
					Type string `json:"type"`
					Const int `json:"const"`
					Description string `json:"description"`
				} `json:"type"`
				Name struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"name"`
			} `json:"properties"`
			Required []string `json:"required"`
			AdditionalProperties bool `json:"additionalProperties"`
			Description string `json:"description"`
			Deprecated string `json:"deprecated"`
		} `json:"APIChannelBase<enum-1225443291-7548-7603-1225443291-7308-8471-1225443291-0-35871732917173>"`
		APIGuildChannelEnum1225443291754876031225443291730884711225443291035871732917173 struct {
			Type string `json:"type"`
			Properties struct {
				ID struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"id"`
				Type struct {
					Type string `json:"type"`
					Const int `json:"const"`
					Description string `json:"description"`
				} `json:"type"`
				Name struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"name"`
				GuildID struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"guild_id"`
				PermissionOverwrites struct {
					Type string `json:"type"`
					Items struct {
						Ref string `json:"$ref"`
					} `json:"items"`
					Description string `json:"description"`
				} `json:"permission_overwrites"`
				Position struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"position"`
				ParentID struct {
					AnyOf []struct {
						Ref string `json:"$ref,omitempty"`
						Type string `json:"type,omitempty"`
					} `json:"anyOf"`
					Description string `json:"description"`
				} `json:"parent_id"`
				Nsfw struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"nsfw"`
			} `json:"properties"`
			AdditionalProperties bool `json:"additionalProperties"`
			Required []string `json:"required"`
			Deprecated string `json:"deprecated"`
		} `json:"APIGuildChannel<enum-1225443291-7548-7603-1225443291-7308-8471-1225443291-0-35871732917173>"`
		APIOverwrite struct {
			Type string `json:"type"`
			Properties struct {
				ID struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"id"`
				Type struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"type"`
				Allow struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"allow"`
				Deny struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"deny"`
			} `json:"properties"`
			Required []string `json:"required"`
			AdditionalProperties bool `json:"additionalProperties"`
			Description string `json:"description"`
			Deprecated string `json:"deprecated"`
		} `json:"APIOverwrite"`
		OverwriteType struct {
			Type string `json:"type"`
			Enum []int `json:"enum"`
			Deprecated string `json:"deprecated"`
		} `json:"OverwriteType"`
		APINewsChannel struct {
			Ref string `json:"$ref"`
			Deprecated string `json:"deprecated"`
		} `json:"APINewsChannel"`
		APIGuildTextChannelEnum12254432917959812212254432917308847112254432910358711915191889 struct {
			Type string `json:"type"`
			Properties struct {
				ID struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"id"`
				Type struct {
					Type string `json:"type"`
					Const int `json:"const"`
					Description string `json:"description"`
				} `json:"type"`
				Name struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"name"`
				GuildID struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"guild_id"`
				PermissionOverwrites struct {
					Type string `json:"type"`
					Items struct {
						Ref string `json:"$ref"`
					} `json:"items"`
					Description string `json:"description"`
				} `json:"permission_overwrites"`
				Position struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"position"`
				ParentID struct {
					AnyOf []struct {
						Ref string `json:"$ref,omitempty"`
						Type string `json:"type,omitempty"`
					} `json:"anyOf"`
					Description string `json:"description"`
				} `json:"parent_id"`
				Nsfw struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"nsfw"`
				LastMessageID struct {
					AnyOf []struct {
						Ref string `json:"$ref,omitempty"`
						Type string `json:"type,omitempty"`
					} `json:"anyOf"`
					Description string `json:"description"`
				} `json:"last_message_id"`
				Topic struct {
					Type []string `json:"type"`
					Description string `json:"description"`
				} `json:"topic"`
				LastPinTimestamp struct {
					Type []string `json:"type"`
					Description string `json:"description"`
				} `json:"last_pin_timestamp"`
			} `json:"properties"`
			AdditionalProperties bool `json:"additionalProperties"`
			Required []string `json:"required"`
			Deprecated string `json:"deprecated"`
		} `json:"APIGuildTextChannel<enum-1225443291-7959-8122-1225443291-7308-8471-1225443291-0-358711915191889>"`
		APITextBasedChannelEnum12254432917959812212254432917308847112254432910358711915191889 struct {
			Type string `json:"type"`
			Properties struct {
				ID struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"id"`
				Type struct {
					Type string `json:"type"`
					Const int `json:"const"`
					Description string `json:"description"`
				} `json:"type"`
				Name struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"name"`
				LastMessageID struct {
					AnyOf []struct {
						Ref string `json:"$ref,omitempty"`
						Type string `json:"type,omitempty"`
					} `json:"anyOf"`
					Description string `json:"description"`
				} `json:"last_message_id"`
			} `json:"properties"`
			AdditionalProperties bool `json:"additionalProperties"`
			Required []string `json:"required"`
			Deprecated string `json:"deprecated"`
		} `json:"APITextBasedChannel<enum-1225443291-7959-8122-1225443291-7308-8471-1225443291-0-358711915191889>"`
		APIChannelBaseEnum12254432917959812212254432917308847112254432910358711915191889 struct {
			Type string `json:"type"`
			Properties struct {
				ID struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"id"`
				Type struct {
					Type string `json:"type"`
					Const int `json:"const"`
					Description string `json:"description"`
				} `json:"type"`
				Name struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"name"`
			} `json:"properties"`
			Required []string `json:"required"`
			AdditionalProperties bool `json:"additionalProperties"`
			Description string `json:"description"`
			Deprecated string `json:"deprecated"`
		} `json:"APIChannelBase<enum-1225443291-7959-8122-1225443291-7308-8471-1225443291-0-358711915191889>"`
		APIGuildChannelEnum12254432917959812212254432917308847112254432910358711915191889 struct {
			Type string `json:"type"`
			Properties struct {
				ID struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"id"`
				Type struct {
					Type string `json:"type"`
					Const int `json:"const"`
					Description string `json:"description"`
				} `json:"type"`
				Name struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"name"`
				GuildID struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"guild_id"`
				PermissionOverwrites struct {
					Type string `json:"type"`
					Items struct {
						Ref string `json:"$ref"`
					} `json:"items"`
					Description string `json:"description"`
				} `json:"permission_overwrites"`
				Position struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"position"`
				ParentID struct {
					AnyOf []struct {
						Ref string `json:"$ref,omitempty"`
						Type string `json:"type,omitempty"`
					} `json:"anyOf"`
					Description string `json:"description"`
				} `json:"parent_id"`
				Nsfw struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"nsfw"`
			} `json:"properties"`
			AdditionalProperties bool `json:"additionalProperties"`
			Required []string `json:"required"`
			Deprecated string `json:"deprecated"`
		} `json:"APIGuildChannel<enum-1225443291-7959-8122-1225443291-7308-8471-1225443291-0-358711915191889>"`
		APIGuildStoreChannel struct {
			Ref string `json:"$ref"`
			Deprecated string `json:"deprecated"`
		} `json:"APIGuildStoreChannel"`
		APIGuildChannelEnum1225443291812383071225443291730884711225443291035871138797936 struct {
			Type string `json:"type"`
			Properties struct {
				ID struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"id"`
				Type struct {
					Type string `json:"type"`
					Const int `json:"const"`
					Description string `json:"description"`
				} `json:"type"`
				Name struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"name"`
				GuildID struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"guild_id"`
				PermissionOverwrites struct {
					Type string `json:"type"`
					Items struct {
						Ref string `json:"$ref"`
					} `json:"items"`
					Description string `json:"description"`
				} `json:"permission_overwrites"`
				Position struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"position"`
				ParentID struct {
					AnyOf []struct {
						Ref string `json:"$ref,omitempty"`
						Type string `json:"type,omitempty"`
					} `json:"anyOf"`
					Description string `json:"description"`
				} `json:"parent_id"`
				Nsfw struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"nsfw"`
			} `json:"properties"`
			AdditionalProperties bool `json:"additionalProperties"`
			Required []string `json:"required"`
			Deprecated string `json:"deprecated"`
		} `json:"APIGuildChannel<enum-1225443291-8123-8307-1225443291-7308-8471-1225443291-0-35871138797936>"`
		APIChannelBaseEnum1225443291812383071225443291730884711225443291035871138797936 struct {
			Type string `json:"type"`
			Properties struct {
				ID struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"id"`
				Type struct {
					Type string `json:"type"`
					Const int `json:"const"`
					Description string `json:"description"`
				} `json:"type"`
				Name struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"name"`
			} `json:"properties"`
			Required []string `json:"required"`
			AdditionalProperties bool `json:"additionalProperties"`
			Description string `json:"description"`
			Deprecated string `json:"deprecated"`
		} `json:"APIChannelBase<enum-1225443291-8123-8307-1225443291-7308-8471-1225443291-0-35871138797936>"`
		APIVoiceChannel struct {
			Type string `json:"type"`
			Properties struct {
				ID struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"id"`
				Type struct {
					AnyOf []struct {
						Type string `json:"type"`
						Const int `json:"const"`
						Description string `json:"description"`
					} `json:"anyOf"`
					Description string `json:"description"`
				} `json:"type"`
				Name struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"name"`
				GuildID struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"guild_id"`
				PermissionOverwrites struct {
					Type string `json:"type"`
					Items struct {
						Ref string `json:"$ref"`
					} `json:"items"`
					Description string `json:"description"`
				} `json:"permission_overwrites"`
				Position struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"position"`
				ParentID struct {
					AnyOf []struct {
						Ref string `json:"$ref,omitempty"`
						Type string `json:"type,omitempty"`
					} `json:"anyOf"`
					Description string `json:"description"`
				} `json:"parent_id"`
				Nsfw struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"nsfw"`
				Bitrate struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"bitrate"`
				UserLimit struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"user_limit"`
				RtcRegion struct {
					Type []string `json:"type"`
					Description string `json:"description"`
				} `json:"rtc_region"`
				VideoQualityMode struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"video_quality_mode"`
			} `json:"properties"`
			AdditionalProperties bool `json:"additionalProperties"`
			Required []string `json:"required"`
			Deprecated string `json:"deprecated"`
		} `json:"APIVoiceChannel"`
		APIGuildChannelEnum12254432918308846812254432917308847112254432910358711830896565Enum1225443291765477111225443291730884711225443291035871121029024 struct {
			Type string `json:"type"`
			Properties struct {
				ID struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"id"`
				Type struct {
					AnyOf []struct {
						Type string `json:"type"`
						Const int `json:"const"`
						Description string `json:"description"`
					} `json:"anyOf"`
					Description string `json:"description"`
				} `json:"type"`
				Name struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"name"`
				GuildID struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"guild_id"`
				PermissionOverwrites struct {
					Type string `json:"type"`
					Items struct {
						Ref string `json:"$ref"`
					} `json:"items"`
					Description string `json:"description"`
				} `json:"permission_overwrites"`
				Position struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"position"`
				ParentID struct {
					AnyOf []struct {
						Ref string `json:"$ref,omitempty"`
						Type string `json:"type,omitempty"`
					} `json:"anyOf"`
					Description string `json:"description"`
				} `json:"parent_id"`
				Nsfw struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"nsfw"`
			} `json:"properties"`
			AdditionalProperties bool `json:"additionalProperties"`
			Required []string `json:"required"`
			Deprecated string `json:"deprecated"`
		} `json:"APIGuildChannel<(enum-1225443291-8308-8468-1225443291-7308-8471-1225443291-0-358711830896565|enum-1225443291-7654-7711-1225443291-7308-8471-1225443291-0-35871121029024)>"`
		APIChannelBaseEnum12254432918308846812254432917308847112254432910358711830896565Enum1225443291765477111225443291730884711225443291035871121029024 struct {
			Type string `json:"type"`
			Properties struct {
				ID struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"id"`
				Type struct {
					AnyOf []struct {
						Type string `json:"type"`
						Const int `json:"const"`
						Description string `json:"description"`
					} `json:"anyOf"`
					Description string `json:"description"`
				} `json:"type"`
				Name struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"name"`
			} `json:"properties"`
			Required []string `json:"required"`
			AdditionalProperties bool `json:"additionalProperties"`
			Description string `json:"description"`
			Deprecated string `json:"deprecated"`
		} `json:"APIChannelBase<(enum-1225443291-8308-8468-1225443291-7308-8471-1225443291-0-358711830896565|enum-1225443291-7654-7711-1225443291-7308-8471-1225443291-0-35871121029024)>"`
		VideoQualityMode struct {
			Type string `json:"type"`
			Enum []int `json:"enum"`
			Deprecated string `json:"deprecated"`
		} `json:"VideoQualityMode"`
		APIGuildCategoryChannel struct {
			Ref string `json:"$ref"`
			Deprecated string `json:"deprecated"`
		} `json:"APIGuildCategoryChannel"`
		APIGuildChannelEnum12254432917776795812254432917308847112254432910358711025724393 struct {
			Type string `json:"type"`
			Properties struct {
				ID struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"id"`
				Type struct {
					Type string `json:"type"`
					Const int `json:"const"`
					Description string `json:"description"`
				} `json:"type"`
				Name struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"name"`
				GuildID struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"guild_id"`
				PermissionOverwrites struct {
					Type string `json:"type"`
					Items struct {
						Ref string `json:"$ref"`
					} `json:"items"`
					Description string `json:"description"`
				} `json:"permission_overwrites"`
				Position struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"position"`
				ParentID struct {
					AnyOf []struct {
						Ref string `json:"$ref,omitempty"`
						Type string `json:"type,omitempty"`
					} `json:"anyOf"`
					Description string `json:"description"`
				} `json:"parent_id"`
				Nsfw struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"nsfw"`
			} `json:"properties"`
			AdditionalProperties bool `json:"additionalProperties"`
			Required []string `json:"required"`
			Deprecated string `json:"deprecated"`
		} `json:"APIGuildChannel<enum-1225443291-7776-7958-1225443291-7308-8471-1225443291-0-358711025724393>"`
		APIChannelBaseEnum12254432917776795812254432917308847112254432910358711025724393 struct {
			Type string `json:"type"`
			Properties struct {
				ID struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"id"`
				Type struct {
					Type string `json:"type"`
					Const int `json:"const"`
					Description string `json:"description"`
				} `json:"type"`
				Name struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"name"`
			} `json:"properties"`
			Required []string `json:"required"`
			AdditionalProperties bool `json:"additionalProperties"`
			Description string `json:"description"`
			Deprecated string `json:"deprecated"`
		} `json:"APIChannelBase<enum-1225443291-7776-7958-1225443291-7308-8471-1225443291-0-358711025724393>"`
		RESTGetAPICurrentUserConnectionsResult struct {
			Type string `json:"type"`
			Items struct {
				Ref string `json:"$ref"`
			} `json:"items"`
			Description string `json:"description"`
			Deprecated string `json:"deprecated"`
		} `json:"RESTGetAPICurrentUserConnectionsResult"`
		APIConnection struct {
			Type string `json:"type"`
			Properties struct {
				ID struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"id"`
				Name struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"name"`
				Type struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"type"`
				Revoked struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"revoked"`
				Integrations struct {
					Type string `json:"type"`
					Items struct {
						Type string `json:"type"`
						Properties struct {
							ID struct {
								Ref string `json:"$ref"`
								Description string `json:"description"`
							} `json:"id"`
							Name struct {
								Type string `json:"type"`
								Description string `json:"description"`
							} `json:"name"`
							Type struct {
								Ref string `json:"$ref"`
								Description string `json:"description"`
							} `json:"type"`
							Enabled struct {
								Type string `json:"type"`
								Description string `json:"description"`
							} `json:"enabled"`
							Syncing struct {
								Type string `json:"type"`
								Description string `json:"description"`
							} `json:"syncing"`
							RoleID struct {
								Ref string `json:"$ref"`
								Description string `json:"description"`
							} `json:"role_id"`
							EnableEmoticons struct {
								Type string `json:"type"`
								Description string `json:"description"`
							} `json:"enable_emoticons"`
							ExpireBehavior struct {
								Ref string `json:"$ref"`
								Description string `json:"description"`
							} `json:"expire_behavior"`
							ExpireGracePeriod struct {
								Type string `json:"type"`
								Description string `json:"description"`
							} `json:"expire_grace_period"`
							User struct {
								Ref string `json:"$ref"`
								Description string `json:"description"`
							} `json:"user"`
							Account struct {
								Ref string `json:"$ref"`
								Description string `json:"description"`
							} `json:"account"`
							SyncedAt struct {
								Type string `json:"type"`
								Description string `json:"description"`
							} `json:"synced_at"`
							SubscriberCount struct {
								Type string `json:"type"`
								Description string `json:"description"`
							} `json:"subscriber_count"`
							Revoked struct {
								Type string `json:"type"`
								Description string `json:"description"`
							} `json:"revoked"`
							Application struct {
								Ref string `json:"$ref"`
								Description string `json:"description"`
							} `json:"application"`
						} `json:"properties"`
						AdditionalProperties bool `json:"additionalProperties"`
					} `json:"items"`
					Description string `json:"description"`
				} `json:"integrations"`
				Verified struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"verified"`
				FriendSync struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"friend_sync"`
				ShowActivity struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"show_activity"`
				Visibility struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"visibility"`
			} `json:"properties"`
			Required []string `json:"required"`
			AdditionalProperties bool `json:"additionalProperties"`
			Description string `json:"description"`
			Deprecated string `json:"deprecated"`
		} `json:"APIConnection"`
		APIGuildInteractionType struct {
			Type string `json:"type"`
			Enum []string `json:"enum"`
			Deprecated string `json:"deprecated"`
		} `json:"APIGuildInteractionType"`
		IntegrationExpireBehavior struct {
			Type string `json:"type"`
			Enum []int `json:"enum"`
			Description string `json:"description"`
			Deprecated string `json:"deprecated"`
		} `json:"IntegrationExpireBehavior"`
		APIIntegrationAccount struct {
			Type string `json:"type"`
			Properties struct {
				ID struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"id"`
				Name struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"name"`
			} `json:"properties"`
			Required []string `json:"required"`
			AdditionalProperties bool `json:"additionalProperties"`
			Description string `json:"description"`
			Deprecated string `json:"deprecated"`
		} `json:"APIIntegrationAccount"`
		APIGuildIntegrationApplication struct {
			Type string `json:"type"`
			Properties struct {
				ID struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"id"`
				Name struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"name"`
				Icon struct {
					Type []string `json:"type"`
					Description string `json:"description"`
				} `json:"icon"`
				Description struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"description"`
				Summary struct {
					Type string `json:"type"`
					Const string `json:"const"`
					Description string `json:"description"`
					Deprecated string `json:"deprecated"`
				} `json:"summary"`
				Bot struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"bot"`
			} `json:"properties"`
			Required []string `json:"required"`
			AdditionalProperties bool `json:"additionalProperties"`
			Description string `json:"description"`
			Deprecated string `json:"deprecated"`
		} `json:"APIGuildIntegrationApplication"`
		ConnectionVisibility struct {
			Type string `json:"type"`
			Enum []int `json:"enum"`
			Deprecated string `json:"deprecated"`
		} `json:"ConnectionVisibility"`
	} `json:"definitions"`
}