type AutoGenerated struct {
	Definitions struct {
		APIApplicationCommandBooleanOption struct {
			Ref string `json:"$ref"`
		} `json:"APIApplicationCommandBooleanOption"`
		APIApplicationCommandOptionBaseEnum15707879492362451570787949030815707879490580 struct {
			Type string `json:"type"`
			Properties struct {
				Type struct {
					Type string `json:"type"`
					Const int `json:"const"`
				} `json:"type"`
				Name struct {
					Type string `json:"type"`
				} `json:"name"`
				Description struct {
					Type string `json:"type"`
				} `json:"description"`
				Required struct {
					Type string `json:"type"`
				} `json:"required"`
			} `json:"properties"`
			Required []string `json:"required"`
			AdditionalProperties bool `json:"additionalProperties"`
		} `json:"APIApplicationCommandOptionBase<enum-1570787949-236-245-1570787949-0-308-1570787949-0-580>"`
		APIApplicationCommandInteractionDataBooleanOption struct {
			Ref string `json:"$ref"`
		} `json:"APIApplicationCommandInteractionDataBooleanOption"`
		APIInteractionDataOptionBaseEnum15707879492362451570787949030815707879490580Boolean struct {
			Type string `json:"type"`
			Properties struct {
				Name struct {
					Type string `json:"type"`
				} `json:"name"`
				Type struct {
					Type string `json:"type"`
					Const int `json:"const"`
				} `json:"type"`
				Value struct {
					Type string `json:"type"`
				} `json:"value"`
			} `json:"properties"`
			Required []string `json:"required"`
			AdditionalProperties bool `json:"additionalProperties"`
		} `json:"APIInteractionDataOptionBase<enum-1570787949-236-245-1570787949-0-308-1570787949-0-580,boolean>"`
	} `json:"definitions"`
}