type AutoGenerated struct {
	Definitions struct {
		APIApplicationCommandChannelOption struct {
			Type string `json:"type"`
			Properties struct {
				Type struct {
					Type string `json:"type"`
					Const int `json:"const"`
				} `json:"type"`
				Name struct {
					Type string `json:"type"`
				} `json:"name"`
				Description struct {
					Type string `json:"type"`
				} `json:"description"`
				Required struct {
					Type string `json:"type"`
				} `json:"required"`
				ChannelTypes struct {
					Type string `json:"type"`
					Items struct {
						Type string `json:"type"`
						Enum []int `json:"enum"`
						Description string `json:"description"`
					} `json:"items"`
				} `json:"channel_types"`
			} `json:"properties"`
			AdditionalProperties bool `json:"additionalProperties"`
			Required []string `json:"required"`
		} `json:"APIApplicationCommandChannelOption"`
		APIApplicationCommandOptionBaseEnum15707879492532621570787949030815707879490580 struct {
			Type string `json:"type"`
			Properties struct {
				Type struct {
					Type string `json:"type"`
					Const int `json:"const"`
				} `json:"type"`
				Name struct {
					Type string `json:"type"`
				} `json:"name"`
				Description struct {
					Type string `json:"type"`
				} `json:"description"`
				Required struct {
					Type string `json:"type"`
				} `json:"required"`
			} `json:"properties"`
			Required []string `json:"required"`
			AdditionalProperties bool `json:"additionalProperties"`
		} `json:"APIApplicationCommandOptionBase<enum-1570787949-253-262-1570787949-0-308-1570787949-0-580>"`
		APIApplicationCommandInteractionDataChannelOption struct {
			Ref string `json:"$ref"`
		} `json:"APIApplicationCommandInteractionDataChannelOption"`
		APIInteractionDataOptionBaseEnum15707879492532621570787949030815707879490580Snowflake struct {
			Type string `json:"type"`
			Properties struct {
				Name struct {
					Type string `json:"type"`
				} `json:"name"`
				Type struct {
					Type string `json:"type"`
					Const int `json:"const"`
				} `json:"type"`
				Value struct {
					Ref string `json:"$ref"`
				} `json:"value"`
			} `json:"properties"`
			Required []string `json:"required"`
			AdditionalProperties bool `json:"additionalProperties"`
		} `json:"APIInteractionDataOptionBase<enum-1570787949-253-262-1570787949-0-308-1570787949-0-580,Snowflake>"`
		Snowflake struct {
			Type string `json:"type"`
			Description string `json:"description"`
		} `json:"Snowflake"`
	} `json:"definitions"`
}