type AutoGenerated struct {
	Definitions struct {
		APIApplicationCommandRoleOption struct {
			Ref string `json:"$ref"`
		} `json:"APIApplicationCommandRoleOption"`
		APIApplicationCommandOptionBaseEnum15707879492632691570787949030815707879490580 struct {
			Type string `json:"type"`
			Properties struct {
				Type struct {
					Type string `json:"type"`
					Const int `json:"const"`
				} `json:"type"`
				Name struct {
					Type string `json:"type"`
				} `json:"name"`
				Description struct {
					Type string `json:"type"`
				} `json:"description"`
				Required struct {
					Type string `json:"type"`
				} `json:"required"`
			} `json:"properties"`
			Required []string `json:"required"`
			AdditionalProperties bool `json:"additionalProperties"`
		} `json:"APIApplicationCommandOptionBase<enum-1570787949-263-269-1570787949-0-308-1570787949-0-580>"`
		APIApplicationCommandInteractionDataRoleOption struct {
			Ref string `json:"$ref"`
		} `json:"APIApplicationCommandInteractionDataRoleOption"`
		APIInteractionDataOptionBaseEnum15707879492632691570787949030815707879490580Snowflake struct {
			Type string `json:"type"`
			Properties struct {
				Name struct {
					Type string `json:"type"`
				} `json:"name"`
				Type struct {
					Type string `json:"type"`
					Const int `json:"const"`
				} `json:"type"`
				Value struct {
					Ref string `json:"$ref"`
				} `json:"value"`
			} `json:"properties"`
			Required []string `json:"required"`
			AdditionalProperties bool `json:"additionalProperties"`
		} `json:"APIInteractionDataOptionBase<enum-1570787949-263-269-1570787949-0-308-1570787949-0-580,Snowflake>"`
		Snowflake struct {
			Type string `json:"type"`
			Description string `json:"description"`
		} `json:"Snowflake"`
	} `json:"definitions"`
}