type AutoGenerated struct {
	Definitions struct {
		ApplicationCommandOptionType struct {
			Type string `json:"type"`
			Enum []int `json:"enum"`
			Description string `json:"description"`
		} `json:"ApplicationCommandOptionType"`
	} `json:"definitions"`
}