type AutoGenerated struct {
	Definitions []struct {
		PartialAPIMessageInteractionGuildMember struct {
			Type string `json:"type"`
			Properties struct {
				Roles struct {
					Type string `json:"type"`
					Items struct {
						Ref string `json:"$ref"`
					} `json:"items"`
					Description string `json:"description"`
				} `json:"roles"`
				PremiumSince struct {
					Type []string `json:"type"`
					Description string `json:"description"`
				} `json:"premium_since"`
				Pending struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"pending"`
				Nick struct {
					Type []string `json:"type"`
					Description string `json:"description"`
				} `json:"nick"`
				Mute struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"mute"`
				JoinedAt struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"joined_at"`
				Deaf struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"deaf"`
				CommunicationDisabledUntil struct {
					Type []string `json:"type"`
					Description string `json:"description"`
				} `json:"communication_disabled_until"`
				Avatar struct {
					Type []string `json:"type"`
					Description string `json:"description"`
				} `json:"avatar"`
			} `json:"properties"`
			Required []string `json:"required"`
			AdditionalProperties bool `json:"additionalProperties"`
			Deprecated string `json:"deprecated"`
		} `json:"PartialAPIMessageInteractionGuildMember,omitempty"`
		Snowflake struct {
			Type string `json:"type"`
			Description string `json:"description"`
		} `json:"Snowflake"`
		APIMessageInteraction struct {
			Type string `json:"type"`
			Properties struct {
				ID struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"id"`
				Type struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"type"`
				Name struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"name"`
				User struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"user"`
				Member struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"member"`
			} `json:"properties"`
			Required []string `json:"required"`
			AdditionalProperties bool `json:"additionalProperties"`
			Description string `json:"description"`
			Deprecated string `json:"deprecated"`
		} `json:"APIMessageInteraction,omitempty"`
		InteractionType struct {
			Type string `json:"type"`
			Enum []int `json:"enum"`
			Description string `json:"description"`
			Deprecated string `json:"deprecated"`
		} `json:"InteractionType"`
		APIUser struct {
			Type string `json:"type"`
			Properties struct {
				ID struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"id"`
				Username struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"username"`
				Discriminator struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"discriminator"`
				Avatar struct {
					Type []string `json:"type"`
					Description string `json:"description"`
				} `json:"avatar"`
				Bot struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"bot"`
				System struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"system"`
				MfaEnabled struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"mfa_enabled"`
				Banner struct {
					Type []string `json:"type"`
					Description string `json:"description"`
				} `json:"banner"`
				AccentColor struct {
					Type []string `json:"type"`
					Description string `json:"description"`
				} `json:"accent_color"`
				Locale struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"locale"`
				Verified struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"verified"`
				Email struct {
					Type []string `json:"type"`
					Description string `json:"description"`
				} `json:"email"`
				Flags struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"flags"`
				PremiumType struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"premium_type"`
				PublicFlags struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"public_flags"`
			} `json:"properties"`
			Required []string `json:"required"`
			AdditionalProperties bool `json:"additionalProperties"`
			Description string `json:"description"`
			Deprecated string `json:"deprecated"`
		} `json:"APIUser,omitempty"`
		UserFlags struct {
			Type string `json:"type"`
			Enum []int `json:"enum"`
			Description string `json:"description"`
			Deprecated string `json:"deprecated"`
		} `json:"UserFlags,omitempty"`
		UserPremiumType struct {
			Type string `json:"type"`
			Enum []int `json:"enum"`
			Description string `json:"description"`
			Deprecated string `json:"deprecated"`
		} `json:"UserPremiumType,omitempty"`
		APIInteractionGuildMember struct {
			Type string `json:"type"`
			Properties struct {
				User struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"user"`
				Nick struct {
					Type []string `json:"type"`
					Description string `json:"description"`
				} `json:"nick"`
				Avatar struct {
					Type []string `json:"type"`
					Description string `json:"description"`
				} `json:"avatar"`
				Roles struct {
					Type string `json:"type"`
					Items struct {
						Ref string `json:"$ref"`
					} `json:"items"`
					Description string `json:"description"`
				} `json:"roles"`
				JoinedAt struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"joined_at"`
				PremiumSince struct {
					Type []string `json:"type"`
					Description string `json:"description"`
				} `json:"premium_since"`
				Deaf struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"deaf"`
				Mute struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"mute"`
				Pending struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"pending"`
				CommunicationDisabledUntil struct {
					Type []string `json:"type"`
					Description string `json:"description"`
				} `json:"communication_disabled_until"`
				Permissions struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"permissions"`
			} `json:"properties"`
			Required []string `json:"required"`
			AdditionalProperties bool `json:"additionalProperties"`
			Description string `json:"description"`
			Deprecated string `json:"deprecated"`
		} `json:"APIInteractionGuildMember,omitempty"`
		APIGuildMember struct {
			Type string `json:"type"`
			Properties struct {
				User struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"user"`
				Nick struct {
					Type []string `json:"type"`
					Description string `json:"description"`
				} `json:"nick"`
				Avatar struct {
					Type []string `json:"type"`
					Description string `json:"description"`
				} `json:"avatar"`
				Roles struct {
					Type string `json:"type"`
					Items struct {
						Ref string `json:"$ref"`
					} `json:"items"`
					Description string `json:"description"`
				} `json:"roles"`
				JoinedAt struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"joined_at"`
				PremiumSince struct {
					Type []string `json:"type"`
					Description string `json:"description"`
				} `json:"premium_since"`
				Deaf struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"deaf"`
				Mute struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"mute"`
				Pending struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"pending"`
				CommunicationDisabledUntil struct {
					Type []string `json:"type"`
					Description string `json:"description"`
				} `json:"communication_disabled_until"`
			} `json:"properties"`
			Required []string `json:"required"`
			AdditionalProperties bool `json:"additionalProperties"`
			Description string `json:"description"`
			Deprecated string `json:"deprecated"`
		} `json:"APIGuildMember,omitempty"`
		APIInteractionResponse struct {
			AnyOf []struct {
				Ref string `json:"$ref"`
			} `json:"anyOf"`
			Description string `json:"description"`
			Deprecated string `json:"deprecated"`
		} `json:"APIInteractionResponse,omitempty"`
		APIInteractionResponsePong struct {
			Type string `json:"type"`
			Properties struct {
				Type struct {
					Type string `json:"type"`
					Const int `json:"const"`
					Description string `json:"description"`
				} `json:"type"`
			} `json:"properties"`
			Required []string `json:"required"`
			AdditionalProperties bool `json:"additionalProperties"`
			Deprecated string `json:"deprecated"`
		} `json:"APIInteractionResponsePong,omitempty"`
		APIInteractionResponseChannelMessageWithSource struct {
			Type string `json:"type"`
			Properties struct {
				Type struct {
					Type string `json:"type"`
					Const int `json:"const"`
					Description string `json:"description"`
				} `json:"type"`
				Data struct {
					Ref string `json:"$ref"`
				} `json:"data"`
			} `json:"properties"`
			Required []string `json:"required"`
			AdditionalProperties bool `json:"additionalProperties"`
			Deprecated string `json:"deprecated"`
		} `json:"APIInteractionResponseChannelMessageWithSource,omitempty"`
		APIInteractionResponseCallbackData struct {
			Type string `json:"type"`
			AdditionalProperties bool `json:"additionalProperties"`
			Properties struct {
				Flags struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"flags"`
				Content struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"content"`
				Tts struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"tts"`
				Embeds struct {
					Type string `json:"type"`
					Items struct {
						Ref string `json:"$ref"`
					} `json:"items"`
					Description string `json:"description"`
				} `json:"embeds"`
				AllowedMentions struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"allowed_mentions"`
				Components struct {
					Type string `json:"type"`
					Items struct {
						Ref string `json:"$ref"`
					} `json:"items"`
					Description string `json:"description"`
				} `json:"components"`
				Attachments struct {
					Type string `json:"type"`
					Items struct {
						Type string `json:"type"`
						AdditionalProperties bool `json:"additionalProperties"`
						Properties struct {
							Filename struct {
								Type string `json:"type"`
								Description string `json:"description"`
							} `json:"filename"`
							ID struct {
								Ref string `json:"$ref"`
								Description string `json:"description"`
							} `json:"id"`
							Description struct {
								Type string `json:"type"`
								Description string `json:"description"`
							} `json:"description"`
						} `json:"properties"`
						Required []string `json:"required"`
					} `json:"items"`
					Description string `json:"description"`
				} `json:"attachments"`
			} `json:"properties"`
			Description string `json:"description"`
			Deprecated string `json:"deprecated"`
		} `json:"APIInteractionResponseCallbackData,omitempty"`
		APIEmbed struct {
			Type string `json:"type"`
			Properties struct {
				Title struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"title"`
				Type struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
					Deprecated string `json:"deprecated"`
				} `json:"type"`
				Description struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"description"`
				URL struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"url"`
				Timestamp struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"timestamp"`
				Color struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"color"`
				Footer struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"footer"`
				Image struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"image"`
				Thumbnail struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"thumbnail"`
				Video struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"video"`
				Provider struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"provider"`
				Author struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"author"`
				Fields struct {
					Type string `json:"type"`
					Items struct {
						Ref string `json:"$ref"`
					} `json:"items"`
					Description string `json:"description"`
				} `json:"fields"`
			} `json:"properties"`
			AdditionalProperties bool `json:"additionalProperties"`
			Description string `json:"description"`
			Deprecated string `json:"deprecated"`
		} `json:"APIEmbed,omitempty"`
		EmbedType struct {
			Type string `json:"type"`
			Enum []string `json:"enum"`
			Description string `json:"description"`
			Deprecated string `json:"deprecated"`
		} `json:"EmbedType,omitempty"`
		APIEmbedFooter struct {
			Type string `json:"type"`
			Properties struct {
				Text struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"text"`
				IconURL struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"icon_url"`
				ProxyIconURL struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"proxy_icon_url"`
			} `json:"properties"`
			Required []string `json:"required"`
			AdditionalProperties bool `json:"additionalProperties"`
			Description string `json:"description"`
			Deprecated string `json:"deprecated"`
		} `json:"APIEmbedFooter,omitempty"`
		APIEmbedImage struct {
			Type string `json:"type"`
			Properties struct {
				URL struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"url"`
				ProxyURL struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"proxy_url"`
				Height struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"height"`
				Width struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"width"`
			} `json:"properties"`
			Required []string `json:"required"`
			AdditionalProperties bool `json:"additionalProperties"`
			Description string `json:"description"`
			Deprecated string `json:"deprecated"`
		} `json:"APIEmbedImage,omitempty"`
		APIEmbedThumbnail struct {
			Type string `json:"type"`
			Properties struct {
				URL struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"url"`
				ProxyURL struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"proxy_url"`
				Height struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"height"`
				Width struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"width"`
			} `json:"properties"`
			Required []string `json:"required"`
			AdditionalProperties bool `json:"additionalProperties"`
			Description string `json:"description"`
			Deprecated string `json:"deprecated"`
		} `json:"APIEmbedThumbnail,omitempty"`
		APIEmbedVideo struct {
			Type string `json:"type"`
			Properties struct {
				URL struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"url"`
				Height struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"height"`
				Width struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"width"`
			} `json:"properties"`
			AdditionalProperties bool `json:"additionalProperties"`
			Description string `json:"description"`
			Deprecated string `json:"deprecated"`
		} `json:"APIEmbedVideo,omitempty"`
		APIEmbedProvider struct {
			Type string `json:"type"`
			Properties struct {
				Name struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"name"`
				URL struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"url"`
			} `json:"properties"`
			AdditionalProperties bool `json:"additionalProperties"`
			Description string `json:"description"`
			Deprecated string `json:"deprecated"`
		} `json:"APIEmbedProvider,omitempty"`
		APIEmbedAuthor struct {
			Type string `json:"type"`
			Properties struct {
				Name struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"name"`
				URL struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"url"`
				IconURL struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"icon_url"`
				ProxyIconURL struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"proxy_icon_url"`
			} `json:"properties"`
			Required []string `json:"required"`
			AdditionalProperties bool `json:"additionalProperties"`
			Description string `json:"description"`
			Deprecated string `json:"deprecated"`
		} `json:"APIEmbedAuthor,omitempty"`
		APIEmbedField struct {
			Type string `json:"type"`
			Properties struct {
				Name struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"name"`
				Value struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"value"`
				Inline struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"inline"`
			} `json:"properties"`
			Required []string `json:"required"`
			AdditionalProperties bool `json:"additionalProperties"`
			Description string `json:"description"`
			Deprecated string `json:"deprecated"`
		} `json:"APIEmbedField,omitempty"`
		APIAllowedMentions struct {
			Type string `json:"type"`
			Properties struct {
				Parse struct {
					Type string `json:"type"`
					Items struct {
						Ref string `json:"$ref"`
					} `json:"items"`
					Description string `json:"description"`
				} `json:"parse"`
				Roles struct {
					Type string `json:"type"`
					Items struct {
						Ref string `json:"$ref"`
					} `json:"items"`
					Description string `json:"description"`
				} `json:"roles"`
				Users struct {
					Type string `json:"type"`
					Items struct {
						Ref string `json:"$ref"`
					} `json:"items"`
					Description string `json:"description"`
				} `json:"users"`
				RepliedUser struct {
					Type string `json:"type"`
					Description string `json:"description"`
					Default bool `json:"default"`
				} `json:"replied_user"`
			} `json:"properties"`
			AdditionalProperties bool `json:"additionalProperties"`
			Description string `json:"description"`
			Deprecated string `json:"deprecated"`
		} `json:"APIAllowedMentions,omitempty"`
		AllowedMentionsTypes struct {
			Type string `json:"type"`
			Enum []string `json:"enum"`
			Description string `json:"description"`
			Deprecated string `json:"deprecated"`
		} `json:"AllowedMentionsTypes,omitempty"`
		APIActionRowComponentAPIMessageActionRowComponent struct {
			Type string `json:"type"`
			Properties struct {
				Type struct {
					Type string `json:"type"`
					Const int `json:"const"`
					Description string `json:"description"`
				} `json:"type"`
				Components struct {
					Type string `json:"type"`
					Items struct {
						Ref string `json:"$ref"`
					} `json:"items"`
					Description string `json:"description"`
				} `json:"components"`
			} `json:"properties"`
			Required []string `json:"required"`
			AdditionalProperties bool `json:"additionalProperties"`
			Description string `json:"description"`
			Deprecated string `json:"deprecated"`
		} `json:"APIActionRowComponent<APIMessageActionRowComponent>,omitempty"`
		APIBaseComponentEnum13302113962910629156133021139628863292951330211396035871105957764 struct {
			Type string `json:"type"`
			Properties struct {
				Type struct {
					Type string `json:"type"`
					Const int `json:"const"`
					Description string `json:"description"`
				} `json:"type"`
			} `json:"properties"`
			Required []string `json:"required"`
			AdditionalProperties bool `json:"additionalProperties"`
			Description string `json:"description"`
			Deprecated string `json:"deprecated"`
		} `json:"APIBaseComponent<enum-1330211396-29106-29156-1330211396-28863-29295-1330211396-0-35871105957764>,omitempty"`
		APIMessageActionRowComponent struct {
			AnyOf []struct {
				Ref string `json:"$ref"`
			} `json:"anyOf"`
			Description string `json:"description"`
			Deprecated string `json:"deprecated"`
		} `json:"APIMessageActionRowComponent,omitempty"`
		APIButtonComponent struct {
			AnyOf []struct {
				Ref string `json:"$ref"`
			} `json:"anyOf"`
			Deprecated string `json:"deprecated"`
		} `json:"APIButtonComponent,omitempty"`
		APIButtonComponentWithCustomID struct {
			Type string `json:"type"`
			Properties struct {
				Type struct {
					Type string `json:"type"`
					Const int `json:"const"`
					Description string `json:"description"`
				} `json:"type"`
				Label struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"label"`
				Style struct {
					AnyOf []struct {
						Type string `json:"type"`
						Const int `json:"const"`
					} `json:"anyOf"`
					Description string `json:"description"`
				} `json:"style"`
				Emoji struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"emoji"`
				Disabled struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"disabled"`
				CustomID struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"custom_id"`
			} `json:"properties"`
			Required []string `json:"required"`
			AdditionalProperties bool `json:"additionalProperties"`
			Deprecated string `json:"deprecated"`
		} `json:"APIButtonComponentWithCustomId,omitempty"`
		APIBaseComponentEnum133021139629157291961330211396288632929513302113960358711131375322 struct {
			Type string `json:"type"`
			Properties struct {
				Type struct {
					Type string `json:"type"`
					Const int `json:"const"`
					Description string `json:"description"`
				} `json:"type"`
			} `json:"properties"`
			Required []string `json:"required"`
			AdditionalProperties bool `json:"additionalProperties"`
			Description string `json:"description"`
			Deprecated string `json:"deprecated"`
		} `json:"APIBaseComponent<enum-1330211396-29157-29196-1330211396-28863-29295-1330211396-0-358711131375322>,omitempty"`
		APIMessageComponentEmoji struct {
			Type string `json:"type"`
			Properties struct {
				ID struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"id"`
				Name struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"name"`
				Animated struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"animated"`
			} `json:"properties"`
			AdditionalProperties bool `json:"additionalProperties"`
			Deprecated string `json:"deprecated"`
		} `json:"APIMessageComponentEmoji,omitempty"`
		APIButtonComponentWithURL struct {
			Type string `json:"type"`
			Properties struct {
				Type struct {
					Type string `json:"type"`
					Const int `json:"const"`
					Description string `json:"description"`
				} `json:"type"`
				Label struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"label"`
				Style struct {
					Type string `json:"type"`
					Const int `json:"const"`
					Description string `json:"description"`
				} `json:"style"`
				Emoji struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"emoji"`
				Disabled struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"disabled"`
				URL struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"url"`
			} `json:"properties"`
			Required []string `json:"required"`
			AdditionalProperties bool `json:"additionalProperties"`
			Deprecated string `json:"deprecated"`
		} `json:"APIButtonComponentWithURL,omitempty"`
		APISelectMenuComponent struct {
			Type string `json:"type"`
			Properties struct {
				Type struct {
					Type string `json:"type"`
					Const int `json:"const"`
					Description string `json:"description"`
				} `json:"type"`
				CustomID struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"custom_id"`
				Options struct {
					Type string `json:"type"`
					Items struct {
						Ref string `json:"$ref"`
					} `json:"items"`
					Description string `json:"description"`
				} `json:"options"`
				Placeholder struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"placeholder"`
				MinValues struct {
					Type string `json:"type"`
					Description string `json:"description"`
					Default int `json:"default"`
				} `json:"min_values"`
				MaxValues struct {
					Type string `json:"type"`
					Description string `json:"description"`
					Default int `json:"default"`
				} `json:"max_values"`
				Disabled struct {
					Type string `json:"type"`
					Description string `json:"description"`
					Default bool `json:"default"`
				} `json:"disabled"`
			} `json:"properties"`
			Required []string `json:"required"`
			AdditionalProperties bool `json:"additionalProperties"`
			Description string `json:"description"`
			Deprecated string `json:"deprecated"`
		} `json:"APISelectMenuComponent,omitempty"`
		APIBaseComponentEnum13302113962919729245133021139628863292951330211396035871663308133 struct {
			Type string `json:"type"`
			Properties struct {
				Type struct {
					Type string `json:"type"`
					Const int `json:"const"`
					Description string `json:"description"`
				} `json:"type"`
			} `json:"properties"`
			Required []string `json:"required"`
			AdditionalProperties bool `json:"additionalProperties"`
			Description string `json:"description"`
			Deprecated string `json:"deprecated"`
		} `json:"APIBaseComponent<enum-1330211396-29197-29245-1330211396-28863-29295-1330211396-0-35871663308133>,omitempty"`
		APISelectMenuOption struct {
			Type string `json:"type"`
			Properties struct {
				Label struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"label"`
				Value struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"value"`
				Description struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"description"`
				Emoji struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"emoji"`
				Default struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"default"`
			} `json:"properties"`
			Required []string `json:"required"`
			AdditionalProperties bool `json:"additionalProperties"`
			Description string `json:"description"`
			Deprecated string `json:"deprecated"`
		} `json:"APISelectMenuOption,omitempty"`
		MessageFlags struct {
			Type string `json:"type"`
			Enum []int `json:"enum"`
			Description string `json:"description"`
			Deprecated string `json:"deprecated"`
		} `json:"MessageFlags,omitempty"`
		APIInteractionResponseDeferredChannelMessageWithSource struct {
			Type string `json:"type"`
			Properties struct {
				Type struct {
					Type string `json:"type"`
					Const int `json:"const"`
					Description string `json:"description"`
				} `json:"type"`
				Data struct {
					Type string `json:"type"`
					Properties struct {
						Flags struct {
							Ref string `json:"$ref"`
							Description string `json:"description"`
						} `json:"flags"`
					} `json:"properties"`
					AdditionalProperties bool `json:"additionalProperties"`
				} `json:"data"`
			} `json:"properties"`
			Required []string `json:"required"`
			AdditionalProperties bool `json:"additionalProperties"`
			Deprecated string `json:"deprecated"`
		} `json:"APIInteractionResponseDeferredChannelMessageWithSource,omitempty"`
		APIInteractionResponseDeferredMessageUpdate struct {
			Type string `json:"type"`
			Properties struct {
				Type struct {
					Type string `json:"type"`
					Const int `json:"const"`
					Description string `json:"description"`
				} `json:"type"`
			} `json:"properties"`
			Required []string `json:"required"`
			AdditionalProperties bool `json:"additionalProperties"`
			Deprecated string `json:"deprecated"`
		} `json:"APIInteractionResponseDeferredMessageUpdate,omitempty"`
		APIInteractionResponseUpdateMessage struct {
			Type string `json:"type"`
			Properties struct {
				Type struct {
					Type string `json:"type"`
					Const int `json:"const"`
					Description string `json:"description"`
				} `json:"type"`
				Data struct {
					Ref string `json:"$ref"`
				} `json:"data"`
			} `json:"properties"`
			Required []string `json:"required"`
			AdditionalProperties bool `json:"additionalProperties"`
			Deprecated string `json:"deprecated"`
		} `json:"APIInteractionResponseUpdateMessage,omitempty"`
		APIApplicationCommandAutocompleteResponse struct {
			Type string `json:"type"`
			Properties struct {
				Type struct {
					Type string `json:"type"`
					Const int `json:"const"`
					Description string `json:"description"`
				} `json:"type"`
				Data struct {
					Ref string `json:"$ref"`
				} `json:"data"`
			} `json:"properties"`
			Required []string `json:"required"`
			AdditionalProperties bool `json:"additionalProperties"`
			Deprecated string `json:"deprecated"`
		} `json:"APIApplicationCommandAutocompleteResponse,omitempty"`
		APICommandAutocompleteInteractionResponseCallbackData struct {
			Type string `json:"type"`
			Properties struct {
				Choices struct {
					Type string `json:"type"`
					Items struct {
						Ref string `json:"$ref"`
					} `json:"items"`
				} `json:"choices"`
			} `json:"properties"`
			AdditionalProperties bool `json:"additionalProperties"`
			Deprecated string `json:"deprecated"`
		} `json:"APICommandAutocompleteInteractionResponseCallbackData,omitempty"`
		APIApplicationCommandOptionChoice struct {
			Type string `json:"type"`
			Properties struct {
				Name struct {
					Type string `json:"type"`
				} `json:"name"`
				Value struct {
					Type []string `json:"type"`
				} `json:"value"`
			} `json:"properties"`
			Required []string `json:"required"`
			AdditionalProperties bool `json:"additionalProperties"`
			Description string `json:"description"`
			Deprecated string `json:"deprecated"`
		} `json:"APIApplicationCommandOptionChoice,omitempty"`
		APIModalInteractionResponse struct {
			Type string `json:"type"`
			Properties struct {
				Type struct {
					Type string `json:"type"`
					Const int `json:"const"`
					Description string `json:"description"`
				} `json:"type"`
				Data struct {
					Ref string `json:"$ref"`
				} `json:"data"`
			} `json:"properties"`
			Required []string `json:"required"`
			AdditionalProperties bool `json:"additionalProperties"`
			Deprecated string `json:"deprecated"`
		} `json:"APIModalInteractionResponse,omitempty"`
		APIModalInteractionResponseCallbackData struct {
			Type string `json:"type"`
			Properties struct {
				CustomID struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"custom_id"`
				Title struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"title"`
				Components struct {
					Type string `json:"type"`
					Items struct {
						Ref string `json:"$ref"`
					} `json:"items"`
					Description string `json:"description"`
				} `json:"components"`
			} `json:"properties"`
			Required []string `json:"required"`
			AdditionalProperties bool `json:"additionalProperties"`
			Description string `json:"description"`
			Deprecated string `json:"deprecated"`
		} `json:"APIModalInteractionResponseCallbackData,omitempty"`
		APIActionRowComponentAPIModalActionRowComponent struct {
			Type string `json:"type"`
			Properties struct {
				Type struct {
					Type string `json:"type"`
					Const int `json:"const"`
					Description string `json:"description"`
				} `json:"type"`
				Components struct {
					Type string `json:"type"`
					Items struct {
						Ref string `json:"$ref"`
					} `json:"items"`
					Description string `json:"description"`
				} `json:"components"`
			} `json:"properties"`
			Required []string `json:"required"`
			AdditionalProperties bool `json:"additionalProperties"`
			Description string `json:"description"`
			Deprecated string `json:"deprecated"`
		} `json:"APIActionRowComponent<APIModalActionRowComponent>,omitempty"`
		APIModalActionRowComponent struct {
			Ref string `json:"$ref"`
			Deprecated string `json:"deprecated"`
		} `json:"APIModalActionRowComponent,omitempty"`
		APITextInputComponent struct {
			Type string `json:"type"`
			Properties struct {
				Type struct {
					Type string `json:"type"`
					Const int `json:"const"`
					Description string `json:"description"`
				} `json:"type"`
				Style struct {
					Ref string `json:"$ref"`
					Description string `json:"description"`
				} `json:"style"`
				CustomID struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"custom_id"`
				Label struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"label"`
				Placeholder struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"placeholder"`
				Value struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"value"`
				MinLength struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"min_length"`
				MaxLength struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"max_length"`
				Required struct {
					Type string `json:"type"`
					Description string `json:"description"`
				} `json:"required"`
			} `json:"properties"`
			Required []string `json:"required"`
			AdditionalProperties bool `json:"additionalProperties"`
			Description string `json:"description"`
			Deprecated string `json:"deprecated"`
		} `json:"APITextInputComponent,omitempty"`
		APIBaseComponentEnum133021139629246292921330211396288632929513302113960358711182532533 struct {
			Type string `json:"type"`
			Properties struct {
				Type struct {
					Type string `json:"type"`
					Const int `json:"const"`
					Description string `json:"description"`
				} `json:"type"`
			} `json:"properties"`
			Required []string `json:"required"`
			AdditionalProperties bool `json:"additionalProperties"`
			Description string `json:"description"`
			Deprecated string `json:"deprecated"`
		} `json:"APIBaseComponent<enum-1330211396-29246-29292-1330211396-28863-29295-1330211396-0-358711182532533>,omitempty"`
		TextInputStyle struct {
			Type string `json:"type"`
			Enum []int `json:"enum"`
			Description string `json:"description"`
			Deprecated string `json:"deprecated"`
		} `json:"TextInputStyle,omitempty"`
		InteractionResponseType struct {
			Type string `json:"type"`
			Enum []int `json:"enum"`
			Description string `json:"description"`
			Deprecated string `json:"deprecated"`
		} `json:"InteractionResponseType,omitempty"`
	} `json:"definitions"`
}