type AutoGenerated struct {
	Definitions []struct {
		GatewayURLQuery struct {
			Type string `json:"type"`
			Properties struct {
				V struct {
					Type string `json:"type"`
				} `json:"v"`
				Encoding struct {
					Type string `json:"type"`
					Enum []string `json:"enum"`
				} `json:"encoding"`
				Compress struct {
					Type string `json:"type"`
					Const string `json:"const"`
				} `json:"compress"`
			} `json:"properties"`
			Required []string `json:"required"`
			AdditionalProperties bool `json:"additionalProperties"`
			Description string `json:"description"`
		} `json:"GatewayURLQuery"`
	} `json:"definitions"`
}