type AutoGenerated struct {
	Definitions Definitions `json:"definitions"`
}
type OAuth2Scopes struct {
	Type string `json:"type"`
	Enum []string `json:"enum"`
	Description string `json:"description"`
}
type Definitions struct {
	OAuth2Scopes OAuth2Scopes `json:"OAuth2Scopes"`
}